### ISSUE TITLE
Compability issues with JsonServiceClient on windows POSReady ( and XP )

### ISSUE THREAD

**Issue by Lennartos** [ServiceStack/Issues#210]
I have an app that runs just fine on win 7/windows server 2012 - but when installed on clients using windows POSReady or windows XP they fail with the following error:
Error Message :Method 'Get' in type 'ServiceStack.JsonServiceClient' from assembly 'ServiceStack.Client, Version=4.0.34.0, Culture=neutral, PublicKeyToken=null' is not implemented.
(Sorry in case of eventual inconsistencies of the error message compared to normal, i manually translated from danish)

I have also seen issues with fresh windows 8.1 tablets although that seems to dissapear after some windows updates / other installs of components. ( they have been delivered without ever the cause beeing found what step exactly fixed it )

**Comment by mythz** [comment]
The typical cause for this exception is that you have a mix of dirty dlls from different versions of ServiceStack libraries, in which case it can be resolved by ensuring that all packages use the same/latest version, also [clearing your NuGet Package Cache](https://github.com/ServiceStack/ServiceStack/wiki/MyGet#clear-nuget-package-cache) if needed. 

Another potential cause is due to the [use of PCL libraries described in this answer](http://stackoverflow.com/a/25863800/85785), in which case you should make sure your .NET framework is patched. [Microsoft released patches to .NET 4.0](http://www.microsoft.com/en-us/download/details.aspx?id=3556) to allow Portable Class Libraries to properly find the appropriate runtime (info [KB2468871](http://support.microsoft.com/kb/2468871)).

**Comment by Lennartos** [comment]
I know all is up to date, so we can eliminate that.
But the the KB248871 did the trick - thanks for that.

**Comment by mythz** [comment]
Cool glad it's sorted.
