### ISSUE TITLE
When specifying a database via the connection string to a redis client manager, it gets overwritten by initial database

### ISSUE THREAD

**Issue by brunomlopes** [ServiceStack/Issues#211]
I want to be able to use different redis databases and specify them via the connection string to a redis client manager.

Looking at the docs on https://github.com/ServiceStack/ServiceStack.Redis#redis-connection-strings and on the code on  https://github.com/ServiceStack/ServiceStack.Redis/blob/master/tests/ServiceStack.Redis.Tests/ConfigTests.cs it is supposed to work, but current testing shows that the database on the connection string ends up not being used.
I can work around it by parsing the connection string and using it as InitialDb, but I don't think this behaviour is expected.

I've created two tests for this and put them up on https://gist.github.com/brunomlopes/f38abac610d0105a1a7b  .
It was tested with ServiceStack.Redis 4.0.34 and 4.0.35

**Comment by mythz** [comment]
Hi Bruno,

Unfortunately it's using the `Db` specified in the redis client manager instead of the endpoint configuration. It would work if you use the new `RedisManagerPool` which gets all its info from the Redis Endpoint / connection string. 

I'll look to see if there's a straight forward solution for `PooledRedisClientManager`, it will likely involve changing Db to a nullable `int?` so it knows not to override the endpoint configuration.

**Comment by mythz** [comment]
Hi Bruno,

This should now be resolved with this commit: https://github.com/ServiceStack/ServiceStack.Redis/commit/e1ab8ce53be67713147a707f5cc6af69f0d19fc7 - where your tests now pass for all Redis Client Managers.

This change is available from v4.0.36+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by brunomlopes** [comment]
Nice, thanks.
