### ISSUE TITLE
Random SerializationException Unable to find assembly 'Npgsql after running for a while

### ISSUE THREAD

**Issue by joshlatimer** [ServiceStack/Issues#214]
I'm currently running a website using ASP.NET on Windows Azure and ServiceStack.OrmLite.PostgreSQL hosted on Heroku which works fine saving/inserting users etc... 

But then I enable a feature of my website which inserts a DepositRequest, inserts a CoinTransaction and updates the User and it runs fine for 30minutes-2hours then it "randomly" crashes the whole website (hosted with ASP.NET on Windows Azure with the database hosted with Heroku) with the following error in the eventlog.xml of windows azure.

http://pastebin.com/zC2c2RVb 

I'm really not sure what causes the SerializationException as the objects I'm inserting/updating seem absolutely fine to me.. and why can it suddenly not find Npgsql after 30-60minutes of running? 

I've tried many things to try and fix this problem ,or even try find out more information about the exception.. but I can't seem to.

**Comment by mythz** [comment]
I've already left a comment on your StackOverflow question here: http://stackoverflow.com/q/27783142/85785

You will need to expand your question to include as much relevant info as possible as it's not possible to reproduce or identify with just that StackTrace. Specifically you should be providing why your app is serializing/deserializing an Npgsql object in the first place? It may due to serializing an object that exposes an Npgsql connection, non-standard IOC registration, passing connections across AppDomains, etc.

**Comment by joshlatimer** [comment]
The objects I'm updating/inserting have no references to an Npgsql object at all and surely if that was the case then it wouldn't work at all? Instead it works for 10-30minutes then that Exception popups which crashes the website.

http://pastebin.com/pyd4W5hX those are the DBUserAccount, DBCoinTransaction and DBDepositRequests that I'm updating/inserting. I don't see any reference to an Npgsql object but perhaps I'm missing something.

**Comment by mythz** [comment]
The exception is a deserialization exception of deserializing an object using the BinaryFormatter, I couldn't guess as what's causing it and none of our libraries uses the BinaryFormatter. But anything wrapping resources like DB/TCP connections shouldn't be serialized so that's what you need to avoid. Since you're using PostgresQL, it's likely serializing an ADO.NET `IDbConnection` wraps an Npgsql DbConnection. Are you storing anything like this in ASP.NET contexts?

The latest pastebin doesn't help identify the issue, but it does show you're using a (static) DB Access inside your serializable POCO's which I would recommend against, ideally your DTO's should be POCO's that are populated outside of the model, e.g. in your Controllers. In case you're doing it anywhere, you shouldn't even keep private instances of DB connections in your models (which BinaryFormatter serializes).

**Comment by mythz** [comment]
If it's bringing the whole AppDomain down it may be due to an unhandled async Exception. Are you using any Async API's in your ASP.NET App?

If you are you may want to use this `TaskExceptionHandlingModule` to catch and log unhandled exceptions: https://evolpin.wordpress.com/2013/05/26/handling-unhandled-task-exceptions-in-asp-net-4/

**Comment by joshlatimer** [comment]
Yep I am, I just tried that and had no luck :(

I also checked through all of my POCO's  and I see no reference to IDbConnection or anything like that at all. Then I checked all of my connections to the database and I'm not updating/saving/inserting anything other than the stuff I want to.

Thanks a lot for your help so far btw, it's greatly appreciated. This issue has been doing my head in for over a week now.

Oh and I also forgot to mention I am using NancyFX

**Comment by joshlatimer** [comment]
Hello, after almost 2 weeks I found the solution to my problem.

A different feature of the website was actually crashing the website.. it was trying to insert an object into the database with a primarykey which already existed in the database... normally that gives an Exception but the function to insert the object was being called inside a NancyFX request which wraps all of the Exceptions up and returns them to the user instead... but it still crashed the website.

Thanks for your help.

**Comment by mythz** [comment]
Ok great, glad it's sorted.
