### ISSUE TITLE
ServiceStackVS integration: generic DTO code-gen broken

### ISSUE THREAD

**Issue by migajek** [ServiceStack/Issues#221]
Hi,
here's the original DTO
![image](https://cloud.githubusercontent.com/assets/581492/5918121/4f8ee350-a625-11e4-9bee-2860250c0075.png)

and here's the one generated by SSVS:
![image](https://cloud.githubusercontent.com/assets/581492/5918114/44fbe71c-a625-11e4-8bf6-983d7f809b9a.png)

**Comment by mythz** [comment]
This should now be fixed with this commit: https://github.com/ServiceStack/ServiceStack/commit/5a6e291f6775e96d2cf5a596e74fd40a14f95d07

Where this code:

```csharp
public abstract class Issue221Base<T>
{
    public T Id { get; set; }

    protected Issue221Base(T id)
    {
        Id = id;
    }
}

public class Issue221Long : Issue221Base<long>
{
    public Issue221Long(long id) : base(id)
    {
    }
}
```

now generates:

```csharp
public partial class Issue221Base<T>
{
        public virtual T Id { get; set; }
}

public partial class Issue221Long : Issue221Base<long>
{
}
```

Note that the Native Types feature only generates the model schemas, i.e. it doesn't emit any implementation code like constructors. Also you should ensure DTO's have parameter-less constructors (or no constructors in which case one is implicitly created) otherwise serializers wont be able to be able to create instances of the type, i.e. it needs to fallback to using ugly hacks to creating instances whilst bypassing all constructors. I also highly [discourage inheritance in DTO's](http://stackoverflow.com/a/10759250/85785) especially when it's just used to [DRY and hide properties](http://stackoverflow.com/a/15369736/85785). 

Having Generic Base types especially are going to problematic in generating code for some languages, they should also be abstract.

Personally I'll always try to avoid this style of inheritance just for the sake of an `Id` property and will avoid the base type completely, if you want generic typed access to the Id you're better off avoiding inheritance and implementing a shared interface like the built-in `IHasId<T>`:

```csharp
public class LongRequest : IHasId<long>
{
    public long Id { get; set; }
}
public class StringRequest : IHasId<string>
{
    public string Id { get; set; }
}
```

But I don't do this either as I can just use the built-in `T.GetId()` extension method for fast access in retrieving the Id value of a property, e.g:

```csharp
var id = o.GetId();
```
