### ISSUE TITLE
Autoquery fails when the same table is joined multiple times.

### ISSUE THREAD

**Issue by AVee** [ServiceStack/Issues#222]
I can't find a way to use AutoQuery in a scenario where the same table is joined twice. The root of this seems to be that AutoQuery generates joins without aliasing the joined tables, resulting in ambiguous columns. It fails both against SQL Server and Sqlite with similar errors. I haven't been able to find a way to work around this.

The code to reproduce this can be found here:
https://gist.github.com/AVee/0cb0dc1912698fcc43df

**Comment by mythz** [comment]
OrmLite (and by extension AutoQuery) doesn't support custom Aliases for Table JOINS so you wont be able to query individual tables. Although your example didn't include the normal case of:

```csharp
[Route("/purchase/query")]
public class QueryPurchase : QueryBase<Purchase>
{
    public int Id { get; set; }
}

client.Get(new QueryPurchase { Id = 1 }).PrintDump();
```

Which will join and populate the multiple self references:

```
{
        Offset: 0,
        Total: 1,
        Results:
        [
                {
                        Id: 1,
                        Description: Sonic Screwdriver,
                        SellerId: 2,
                        BuyerId: 1,
                        Buyer:
                        {
                                Id: 1,
                                Name: Rose Tyler
                        },
                        Seller:
                        {
                                Id: 2,
                                Name: Martha Jones
                        }
                }
        ]
}
```

There's a new `CustomJoin` API in OrmLite that will allow you to specify your own [Aliases on JOINS](http://stackoverflow.com/a/28031793/85785).

### Using a Custom AutoQuery implementation

Since you can't query on the multiple self referenced tables, one way to do this is to use a Custom AutoQuery implementation where you can query the child table Id's in the custom AutoQuery implementation.

To do this we'll create an additional "backing" AutoQuery DTO `QueryPurchase` containing the properties that AutoQuery can handle whilst the `CustomPurchase` AutoQuery remains the public facing API that you want to expose for this service, e.g:

```csharp
[Alias("Purchase")]
public class CustomPurchase : QueryBase<Purchase>
{
    public int? Id { get; set; }
    public string Description { get; set; }
    public string SellerName { get; set; }
    public string BuyerName { get; set; }
}

public class QueryPurchase : QueryBase<Purchase>
{
    public int? Id { get; set; }
    public string Description { get; set; }
    public List<int> BuyerIds { get; set; }
    public List<int> SellerIds { get; set; }
}
```

And in your custom AutoQuery implementation you can fetch the appropriate Buyer and Seller Id's and add them to the backing `QueryPurchase` Query, e.g:

```csharp
public QueryResponse<Purchase> Any(CustomPurchase request)
{
    var qPurchase = request.ConvertTo<QueryPurchase>();

    if (request.BuyerName != null)
    {
        qPurchase.BuyerIds = Db.Column<int>(Db.From<Person>()
            .Where(x => x.Name == request.BuyerName)
            .Select(x => x.Id));
    }

    if (request.SellerName != null)
    {
        qPurchase.SellerIds = Db.Column<int>(Db.From<Person>()
            .Where(x => x.Name == request.SellerName)
            .Select(x => x.Id));
    }

    var q = AutoQuery.CreateQuery(qPurchase, Request.GetRequestParams());

    return AutoQuery.Execute(qPurchase, q);
}
```

AutoQuery understands Collection properties like `BuyerIds` and performs the appropriate query on `BuyerId`.

So now when calling this Service:

```csharp
client.Get(new CustomPurchase { BuyerName = "Rose Tyler" }).PrintDump();
```

It will print the desired:

```
{
        Offset: 0,
        Total: 1,
        Results:
        [
                {
                        Id: 1,
                        Description: Sonic Screwdriver,
                        SellerId: 2,
                        BuyerId: 1,
                        Buyer:
                        {
                                Id: 1,
                                Name: Rose Tyler
                        },
                        Seller:
                        {
                                Id: 2,
                                Name: Martha Jones
                        }
                }
        ]
}
```

### Appending Custom Conditions

In similar spirit another way to approach this would be to add customized conditions to the AutoQuery itself, for this we no longer need the `BuyerIds` or `SellerIds` properties, e.g:

```csharp
public class QueryPurchase : QueryBase<Purchase>
{
    public int? Id { get; set; }
    public string Description { get; set; }
}
```

The `QueryPurchase` DTO holds the `Purchase` table properties that AutoQuery can handle minus the `SellerName` and `BuyerName` which needs to be special-cased, e.g:

```csharp
public QueryResponse<Purchase> Any(CustomPurchase request)
{
    //Copy only the properties that AutoQuery can handle
    var qPurchase = request.ConvertTo<QueryPurchase>();
    var q = AutoQuery.CreateQuery(qPurchase, Request.GetRequestParams());

    //Add Custom SQL Conditions for each Custom Query
    if (request.BuyerName != null)
        q.UnsafeWhere("BuyerId IN (SELECT Id FROM Person WHERE Name = {0})", request.BuyerName);

    if (request.SellerName != null)
        q.UnsafeWhere("SellerId IN (SELECT Id FROM Person WHERE Name = {0})", request.SellerName);

    return AutoQuery.Execute(qPurchase, q);
}
```

This is similar to the above custom AutoQuery implementation except it gets added to the single AutoQuery query.

Likewise calling this Service:

```csharp
client.Get(new CustomPurchase { BuyerName = "Rose Tyler" }).PrintDump();
```

Also prints the desired:

```
{
        Offset: 0,
        Total: 1,
        Results:
        [
                {
                        Id: 1,
                        Description: Sonic Screwdriver,
                        SellerId: 2,
                        BuyerId: 1,
                        Buyer:
                        {
                                Id: 1,
                                Name: Rose Tyler
                        },
                        Seller:
                        {
                                Id: 2,
                                Name: Martha Jones
                        }
                }
        ]
}
```

> Note I've changed `int Id` to `int? Id` so it doesn't automatically add a `Id == 0` query when no Id is supplied.

To support this I've added new `UnsafeWhere` API's to OrmLite's `SqlExpression` in order to be able to add unverified raw SQL like the sub SELECT added above. The parameters still get escaped which will prevent any SQL Injections. This change is available from **v4.0.37+** that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

---

Can you do me a favor and also ask this question on StackOverflow? http://stackoverflow.com/questions/ask

As I ended up spending a fair bit of time on this answer and don't want this information which can help others get lost and buried in this issues list. Thanks!

**Comment by AVee** [comment]
There you go: http://stackoverflow.com/questions/28189930/

I've also taken a look at the OrmLite code, because I think it might be usefull if OrmLite would generate an alias for each table within a query. If every table which participates in the query would be referred to by an alias (always) issues like this should go away. Am I right in assuming this would all be contained within SqlExpression? I'd be willing to take a look and see if I can make that work, but I guess you've got an opinion about that as well :)

**Comment by mythz** [comment]
Brilliant just answered, thx!

Sure you can have a look to see if it's not too disruptive to add support for it, but I want to avoid adding complexity or confusion to the existing API's. Yeah SqlExpression is the guts of it, it's split out into a couple of partial classes and there's an overloads for the different RDBMS providers but they're mostly lightweight.
