### ISSUE TITLE
Select where date is in the future - using UTC - returns nothing (using SQLite provider)

### ISSUE THREAD

**Issue by marko444** [ServiceStack/Issues#226]
I am inserting a record with a future datetime of Now + 1 hour (kind = UTC) into a SQLite database. Value is stored correctly into a database. 
However when issuing a select to return all records in the future (using Now; kind = UTC)  the record is not found.

This sees like a bug. Can you confirm?

```c#
    public class TestClass
    {
        public string Name { get; set; }
        public DateTime ExpirationDate { get; set; }
    }

    public class DataTimeConditionTest
    {

        [Fact]
        public void Test_DateTime_Select()
        {
            var dbFactory = new OrmLiteConnectionFactory(":memory:", dialectProvider: SqliteDialect.Provider);
            using (var db = dbFactory.OpenDbConnection())
            {
                // Create table
                db.DropAndCreateTable<TestClass>();
                
                // Insert test data ()
                db.Insert(new TestClass { Name = "Test name", ExpirationDate = DateTime.UtcNow.AddHours(1) });

                // Select item by date in the future
                var result = db.Select<TestClass>(q => q.ExpirationDate > DateTime.UtcNow);

                // Select should return 1 record
                Assert.Equal(1, result.Count);
            }
        }
    }
```

**Comment by mythz** [comment]
I've just added this test which works for Sqlite and all other RDBMS providers:
https://github.com/ServiceStack/ServiceStack.OrmLite/commit/a71b25bfa95b208d4c3c90f82fbdeffc4bf37ff1

This must be due to another issue. Can you print out the SQL with:

```csharp
db.Insert(new TestClass { Name = "Test name", ExpirationDate = DateTime.UtcNow.AddHours(1) });
db.GetLastSql().Print();

var result = db.Select<TestClass>(q => q.ExpirationDate > DateTime.UtcNow);
db.GetLastSql().Print();
```

**Comment by marko444** [comment]
Results from my test:
```c#
    DateTime.UtcNow = 2015-02-03T05:55:35.2451610Z
    
    INSERT INTO "TestClass" ("Name","ExpirationDate") VALUES (@Name,@ExpirationDate)
    
    SELECT "Name", "ExpirationDate" 
    FROM "TestClass"
    WHERE ("ExpirationDate" > '2015-02-03 06:55:35.2921818')
```

**Comment by mythz** [comment]
Can you try again using the latest **v4.0.37+** that's on MyGet: https://github.com/ServiceStack/ServiceStack/wiki/MyGet

**Comment by marko444** [comment]
Observations from latest v4.0.37+

If your test is passing then you might have a problem with DateTime timer resolution (your UtcNow might have the same value for the whole test).

## SQL Server

```c#
UtcNow = 2015-02-04T09:13:17.9910511Z
UtcNow.AddHours(1) = 2015-02-04T10:13:17.9910511Z (this is the value we insert into the database)
```

Value in database after it is inserted by OrmLite "2015-02-04 10:13:17.990" obtained from Sql manager. 
**Correct.**

Value when read by OrmLite = {4.2.2015 10:13:17} Kind=Unspecified
**Correct.**

Query generated by OrmLite when searching with UtcNow:
```c#
    db.Select<TestDate>(q => q.ExpiryDate > DateTime.UtcNow);
    >>>
    SELECT "Name", "ExpiryDate" FROM "TestDate" WHERE ("ExpiryDate" > '20150204 09:13:18.037')
```
**Correct.**

Query generated by OrmLite when searching with Now:
```c#
    db.Select<TestDate>(q => q.ExpiryDate > DateTime.Now);
    >>>
    SELECT "Name", "ExpiryDate" FROM "TestDate"WHERE ("ExpiryDate" > '20150204 10:13:18.053')
```
**Correct.**

**YOUR TEST PASSES OK.**

## SQLITE 

```c#
UtcNow = 2015-02-04T09:17:32.6961901Z
UtcNow.AddHours(1) = 2015-02-04T10:17:32.6961901Z (this is the value we insert into the database)
```

Value in database after it is inserted by OrmLite "2015-02-04 10:17:32.6961901" obtained from SqlLiteSpy.
**Correct.**

Value when read by OrmLite = {4.2.2015 10:17:32} Kind=Unspecified 
**Correct.**

Query generated by OrmLite when searching with UtcNow:
```c#
    db.Select<TestDate>(q => q.ExpiryDate > DateTime.UtcNow);
    >>>
    SELECT "Name", "ExpiryDate" FROM "TestDate" WHERE ("ExpiryDate" > '2015-02-04 10:17:32.7274431')
```
:boom: **Wrong. The value should be  '09:17:32.7274431'.**

Query generated by OrmLite when searching with Now:
```c#
    db.Select<TestDate>(q => q.ExpiryDate > DateTime.Now);
    >>>
    SELECT "Name", "ExpiryDate" FROM "TestDate" WHERE ("ExpiryDate" > '2015-02-04 10:17:32.7430709')
```
**Correct.**

**YOUR TEST FAILES.**

**Comment by mythz** [comment]
Note: Sqlite works different to other RDBMS's...

There is no DateTime type in Sqlite, Date's are stored as a string, they don't include the Kind so they're converted to and assumed to be stored in Local time.

This also means that when querying, the DateTime value is also converted to LocalTime. 

So in actuality both these queries are correct:

```csharp
db.Select<TestDate>(q => q.ExpiryDate > DateTime.UtcNow);
db.Select<TestDate>(q => q.ExpiryDate > DateTime.Now);
```

i.e. both queries should generate the same SQL with the queried DateTime converted to LocalTime so it matches what value is stored in Sqlite (LocalTime).

I've just notice that the parameterized INSERT values wasn't converting the value to LocalTIme which should now be resolved with this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/ed9cae24ac8cedb0fa5563e893c3032e0b4d9b75

This change has now finished deploying to MyGet, since you have v4.0.37 already installed you'll need to delete your `/packages` folder and [Clear your NuGet Cache](https://github.com/ServiceStack/ServiceStack/wiki/MyGet#redownloading-myget-packages) to download the latest v4.0.37 version.

**Comment by marko444** [comment]
I am not sure if it is correct to automatically convert from utc into local before saving to the database.
But for my testing scenarios this fix works as expected!

**Comment by mythz** [comment]
Cool, glad it's sorted.

**Comment by herberav** [comment]
I have a similar problem. I'm using in memory database to perform unit testing, I'm storing dates as UTC but when I read a the record the DateTime fields are with the system timezone. I tried to set the DateTimeKind 

`            var date = DateTime.SpecifyKind(record.ExpiresAt, DateTimeKind.Utc);
`
Because I always need to use UTC to compare with other values, but the date continues with the system timezone. 

When I use SQL server that doesn't happen, the date fields are retrieved as UTC. 

Do you have any suggestions?

**Comment by mythz** [comment]
@herberav Sqlite stores DateTime's differently as mentioned above but you can try registering a [custom TypeConverter](https://github.com/ServiceStack/ServiceStack.OrmLite/wiki/OrmLite-Type-Converters) for DateTime which will let you take over DateTime handling in Sqlite. You can inherit from [SqliteDateTimeConverter](https://github.com/ServiceStack/ServiceStack.OrmLite/blob/master/src/ServiceStack.OrmLite.Sqlite/Converters/SqliteDateTimeConverter.cs) to override existing behavior.
