### ISSUE TITLE
ServiceStack.Interfaces.csproj is looking for servicestack-sn.pfx

### ISSUE THREAD

**Issue by BrianARice** [ServiceStack/Issues#234]
The project file ServiceStack.Interfaces.csproj is looking for a file that doesn't exist: servicestack-sn.pfx

Also, oddly, unlike all of the other projects I have added... this one has (Portable) next to it.

Thanks!

**Comment by mythz** [comment]
The ServiceStack.Interfaces project is the only dll that's signed by default since the start of v4, details at: https://github.com/ServiceStack/ServiceStack/blob/master/docs/2014/release-notes.md#servicestackinterfaces-is-now-strong-named

It's also the only dll that could be converted to a pure PCL dll without needing external implementation adapters for specific platforms, announced at:
https://github.com/ServiceStack/ServiceStack/blob/master/docs/2014/release-notes.md#improved-pcl-story

Note: ServiceStack.Interfaces project is disconnected from the rest of the solution and all other projects references the pre-built dll in `/lib`.
