### ISSUE TITLE
License expiration

### ISSUE THREAD

**Issue by theonlylawislove** [ServiceStack/Issues#238]
I noticed my license says "valid until". Does that mean that, at that point in time, the run time will throw license exceptions?

Will this single license work forever, without modification?

![image](https://cloud.githubusercontent.com/assets/523150/6276549/a994600e-b855-11e4-9c17-a91ca3a0b68a.png)

**Comment by mythz** [comment]
No this wont affect existing versions of ServiceStack. Your license will continue to work unmodified on your existing versions of ServiceStack.

The maintenance expiry is used to work out whether you're eligible to use newer versions of ServiceStack. Each developer license comes with 12 months of software updates and support from the date of purchase. You can use your license with the last version of ServiceStack released before your maintenance expires, in perpetuity.

**Comment by TheLastTech** [comment]
Yeah, can you do something about nuget not having older servicestack libraries? It's trying to force 5.8 which is trying to force a new license.

**Comment by mythz** [comment]
@TheLastTech Don't use a Version wildcard and pin your dependencies to the specific Version you want.

**Comment by TheLastTech** [comment]
```
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="NLog" Version="4.6.8" />
    <PackageReference Include="NLog.Web" Version="4.9.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="4.9.0" />
    <PackageReference Include="ServiceStack" Version="[5.7.1,5.8)" />
    <PackageReference Include="ServiceStack.Logging.NLog" Version="5.7.1" />
    <PackageReference Include="ServiceStack.Logging.NLog.Core" Version="5.7.1" />
    <PackageReference Include="ServiceStack.OrmLite.Core" Version="5.7.1" />
    <PackageReference Include="ServiceStack.OrmLite.PostgreSQL.Core" Version="5.7.1" />
    <PackageReference Include="ServiceStack.Server" Version="[5.7.1,5.8)" />

```

thanks mythz for the response. For anyone else who has to deal with this just copy your service stack package from server to server and use semver [ Inclusive and , )excluse like above.

**Comment by TheLastTech** [comment]
and to note, I was't using wildcard. I had to set [ ) specifics which is damn annoying considering I've gotten like 10 people to buy a license and now I'm fearing if I ever have to do upgrade

**Comment by mythz** [comment]
You should only be using the same version for all ServiceStack packages which should reference the official release version you want, e.g. for v5.7:

```xml
<PackageReference Include="ServiceStack.Logging.NLog" Version="5.7.0" />
```

Have a read of the [Versioning Scheme](https://docs.servicestack.net/myget#versioning-scheme) for pre-release packages, i.e. all Patch versions ending in an odd number, e.g. v5.7.1 references the pre-release version on MyGet, but the only pre-release version that exists on MyGet is the latest pre-release version, currently v5.8.1, so v5.7.1 doesn't exist.

Also don't reference `.Core` packages in the same project as normal packages (without the .Core suffix). The `.Core` packages should only be used in projects where you need to force the use of .NET Standard libraries, typically if you're trying to run [ASP.NET Core on the .NET Framework](https://docs.servicestack.net/templates-corefx#reference-core-packages), otherwise reference the normal packages without the `.Core` suffix.

All together your ServiceStack references should look like:

```xml
<PackageReference Include="ServiceStack" Version="5.7.0" />
<PackageReference Include="ServiceStack.Logging.NLog" Version="5.7.0" />
<PackageReference Include="ServiceStack.OrmLite" Version="5.7.0" />
<PackageReference Include="ServiceStack.OrmLite.PostgreSQL" Version="5.7.0" />
<PackageReference Include="ServiceStack.Server" Version="5.7.0" />
```
