### ISSUE TITLE
Bussines object stored in multiple tables

### ISSUE THREAD

**Issue by OlegNadymov** [ServiceStack/Issues#239]
For example:
```C#
[Alias("base_table")]
public class BaseObject
{
    [AutoIncrement]
    [Alias("_id")]
    public int Id { get; set; }

    [Alias("_name")]
    [StringLength(250)]
    public string Name { get; set; }
}

[Alias("apply_table")]
public class ApplyObject : BaseObject
{
    [Alias("_some_property1")]
    [StringLength(250)]
    public string SomeProperty1 { get; set; }
}
```

For my case ORMLite methods (e.g., ```connectionDB.Select< ApplyObject>()```) generate SQL what contains only single table (```apply_table```):
```SQL
Select "apply_table"."_id", "apply_table"."_name", "apply_table"."_some_property1"
From "apply_table"
```

But correct SQL:
```SQL
Select "base_table"."_id", "base_table"."_name", "apply_table"."_some_property1"
From "apply_table"
Inner Join "base_table" on "base_table"._id =  "apply_table"._id
```

What can I do in my case? How I can change my code for correct all CRUD operations?

**Comment by mythz** [comment]
No, OrmLite doesn't split its inheritance tree across multiple tables like this, it always assumes the 1 class is looking at the same table. 

If you want it to join on 2 separate tables, each class needs to be joined as 2 separate tables, you can then select results from both tables into a custom type that [unambiguously references the fields from both tables](https://github.com/ServiceStack/ServiceStack.OrmLite#selecting-multiple-columns-across-joined-tables), e.g:

```csharp
class JoinedObject {
    public int Id { get; set; }
    public string Name { get; set; }
    public int ApplyObjectId { get; set; }
    public string ApplyObjectName { get; set; }
    public string SomeProperty1 { get; set; }
}
var results = db.From<BaseObject>()
    .Join<ApplyObject>((b,a) => b.Id == a.Id)
    .SelectInto<JoinedObject>();
results.PrintDump();
```

Since the relation between your 2 tables can't be inferred (i.e doesn't follow [implicit reference conventions](https://github.com/ServiceStack/ServiceStack.OrmLite#reference-conventions)) you'll need an explicit join for this.
