### ISSUE TITLE
cannot view the site:http://mvc.servicestack.net/ and http://webforms.servicestack.net/

### ISSUE THREAD

**Issue by dongeast** [ServiceStack/Issues#246]
FATAL: 3D000: database "test" does not exist 
  Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

 Exception Details: Npgsql.NpgsqlException: FATAL: 3D000: database "test" does not exist

Source Error: 

 An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

**Comment by mythz** [comment]
The Connection Strings are updated now.

thx for reporting!

**Comment by dongeast** [comment]
Server=localhost;Port=5432;User Id=test;Password=test;Database=test;Pooling=true;MinPoolSize=0;MaxPoolSize=200

How to download the database test?
I can not run MVC sample.

**Comment by mythz** [comment]
It's looking for a local PostgreSQL database called `test`.

If you don't have PostgreSQL installed you can change it to use any [supported OrmLite database](https://github.com/ServiceStack/ServiceStack.OrmLite#8-flavours-of-ormlite-is-on-nuget), e.g Sqlite will work without a network database.

**Comment by dongeast** [comment]
I cannot find any database file in the source code.
could you tell me about the local database file, sqlite is the best choice.

**Comment by mythz** [comment]
This example uses PostgreSQL it doesn't have Sqlite configured.

To configure it you would need to install the [OrmLite Sqlite Provider](https://github.com/ServiceStack/ServiceStack.OrmLite#8-flavours-of-ormlite-is-on-nuget).

    PM> Install-Package ServiceStack.OrmLite.Sqlite.Mono

Then you would change the configuration to use Sqlite instead of PosgreSQL, e.g:

```csharp
var connString = "~/App_Data/db.sqlite".MapServerPath(); 
//var connString = ":memory:"; //alternative use in memory database 
container.Register<IDbConnectionFactory>(
    new OrmLiteConnectionFactory(connString, SqliteDialect.Provider));
```

You can look at many of the other [Live Demos](https://github.com/ServiceStackApps/LiveDemos) to see how to configure OrmLite with Sqlite, e.g here's the config for HttpBenchmarks which [supports switching between PostgreSQL or Sqlite](https://github.com/ServiceStackApps/HttpBenchmarks/blob/master/src/BenchmarksAnalyzer/Global.asax.cs#L42)
