### ISSUE TITLE
License key issue

### ISSUE THREAD

**Issue by juhlle00** [ServiceStack/Issues#277]
I just purchase ServiceStack Text indie license and I plugged key into my current webapi all three way (web.config, begore init() method, and text file...) and I install package from nuget (it came with the v4.0.40.0). Package installed ServiceStack, TEXT, COMMON, CLIENT and INTERFACE.
But keep telling me 'The free-quota limit on '10 ServiceStack Operations' has been reached'  upgrade to Commercial version. I don't know what is wrong.

**Comment by mythz** [comment]
This is because you've only purchased the **[ServiceStack.Text](https://servicestack.net/text)** license which only covers and lifts the free-quotas for the serializers in the **ServiceStack.Text** library.
The exception you're getting is because you've exceeded the free-quota for the ServiceStack Web Service Framework which requires the full license listed at https://servicestack.net/pricing
