### ISSUE TITLE
Exception with newlines break json format

### ISSUE THREAD

**Issue by bcffx** [ServiceStack/Issues#285]
Json encoding of exceptions with newlines in the message or stacktrace has recently been broken (may be more widespread, haven't tested).

```csharp
    public object Get( TestDto request )
    {
      throw new Exception( "Line1\nLine2" );
    }
```

Nuget v4.0.40.0 works:

```javascript
{
  "ResponseStatus": {
    "ErrorCode": "Exception",
    "Message": "Line1\nLine2",
    "StackTrace": "[TestDto: 19/05/2015 6:25:41 AM]:\n[REQUEST: {}]\nSystem.Exception: Line1\nLine2\r\n   at TestServiceStack.TestService.Get(TestDto request) in c:\\VS Projects\\TestServiceStackNuget\\TestServiceStackNuget\\AppHost.cs:line 66\r\n   at lambda_method(Closure , Object , Object )\r\n   at ServiceStack.Host.ServiceRunner`1.Execute(IRequest request, Object instance, TRequest requestDto)",
    "Errors": []
  }
}
```

Current git source breaks:

```javascript
can't parse JSON.  Raw result:

{"ResponseStatus":{"ErrorCode":"Exception","Message":"Line1\
Line2","StackTrace":"[TestDto: 19/05/2015 6:28:10 AM]:\
[REQUEST: {}]\
System.Exception: Line1\
Line2\
\
   at TestServiceStack.TestService.Get(TestDto request) in c:\\VS Projects\\TestServiceStack\\TestServiceStack\\AppHost.cs:line 66\
\
   at lambda_method(Closure , Object , Object )\
\
   at ServiceStack.Host.ServiceRunner`1.Execute(IRequest request, Object instance, TRequest requestDto) in c:\\github\\ServiceStack\\src\\ServiceStack\\Host\\ServiceRunner.cs:line 99","Errors":[]}}
```

**Comment by mythz** [comment]
ahh looks like the issue was introduced with this commit: https://github.com/ServiceStack/ServiceStack.Text/commit/5d233402dcde7bd08a409ba33d0bea9266e58984
and just recently resolved with this commit: https://github.com/bhdebrito/ServiceStack.Text/commit/51c64075d487fcde878d0ca0d4aaecd23fa093b5

This change has now finished deploying to MyGet, if you've already got v4.0.41 of MyGet installed you'll need to [clear out your NuGet packages cache](https://github.com/ServiceStack/ServiceStack/wiki/MyGet#redownloading-myget-packages) to download the latest version.

thx for reporting!
