### ISSUE TITLE
SaltedHash isn't thread safe when using SHA256Managed

### ISSUE THREAD

**Issue by georgehemmings** [ServiceStack/Issues#292]
Hi

SaltedHash uses a single instance of SHA256Managed, but SHA256Managed isn't thread safe. https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/Auth/SaltedHash.cs#L30

I've tested SHA256Managed (outside of SS) using multiple threads, and race conditions can occur causing ComputeHash to return incorrect hashes.

Unless I'm misunderstanding something, this could result in failed logins when the password is correct.

**Comment by mythz** [comment]
Most instances aren't threadsafe. Do know of an example in ServiceStack where this instance is used across multiple threads?

**Comment by georgehemmings** [comment]
IHashProvider is resolved once, as an instance field in OrmLiteAuthRepository. https://github.com/ServiceStack/ServiceStack/blob/bf1ba77aad788da5da42ab558469f64e6a3602ba/src/ServiceStack.Server/Auth/OrmLiteAuthRepository.cs#L35

SaltedHash is the default implementation of IHashProvider, it creates a single instance of SHA256Managed. 

As OrmLiteAuthRepository is usually registered in the IoC container as a singleton in could be used by multiple requests, potentially concurrently from different threads.

**Comment by mythz** [comment]
Yep cool, looks like this was the only place I could find that maintained its own instance of `IHashProvider` - now changed to resolve from `HostContext.AppHost.GetHashProvider()` on each usage in this commit: https://github.com/ServiceStack/ServiceStack/commit/19608fb5b658d845e808febeb874d4bf2e00fd7d

**Comment by georgehemmings** [comment]
Awesome. Can I just ask why you decided to introduce the GetHashProvider factory method instead of using the IOC container? I'm just interested as to the reason :)

**Comment by mythz** [comment]
Yeah that's a good point, I didn't want to make this a normal dependency property on existing classes as the dependencies could be registered with different lifetimes and didn't want to impact how dependencies were registered (i.e. manual/auto wiring). But I could've also just resolve it from the IOC instead of a typed method so I've switched to do that in this commit: https://github.com/ServiceStack/ServiceStack/commit/cb65714f0e64da2cfded50ff2a02914c297029d0 

Normally I wouldn't do a breaking change like this but ok here since this hasn't been released yet.

This change is available from v4.0.41+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
