### ISSUE TITLE
Multi-threaded/locking issue in OrmLite.ModelDefinition.GetFieldDefinitionMap

### ISSUE THREAD

**Issue by marko444** [ServiceStack/Issues#313]
Function GetFieldDefinitionMap can return empty field definition dictionary when called from different threads at the same time (during application startup).

```c#
public Dictionary<string, FieldDefinition> GetFieldDefinitionMap(Func<string, string> sanitizeFieldName)
{
	if (fieldDefinitionMap == null || fieldNameSanitizer != sanitizeFieldName)
	{
		lock (fieldDefLock)
		{
			if (fieldDefinitionMap == null || fieldNameSanitizer != sanitizeFieldName)
			{
				fieldDefinitionMap = new Dictionary<string, FieldDefinition>(StringComparer.OrdinalIgnoreCase);
				fieldNameSanitizer = sanitizeFieldName;
				foreach (var fieldDef in FieldDefinitionsArray)
				{
					fieldDefinitionMap[sanitizeFieldName(fieldDef.FieldName)] = fieldDef;
				}
			}
		}
	}
	return fieldDefinitionMap;
}

```
1. Thread A enters lock and creates fieldDefinitionMap
2. Thread B returns empty fieldDefinitionMap (dictionary has not been initialized yet)

**Comment by mythz** [comment]
Thread B doesn't modify the collection when it enters the lock since fieldDefinitionMap is no longer null? It's only initialized and populated inside the lock.

**Comment by marko444** [comment]
>Thread B doesn't modify the collection when it enters the lock since fieldDefinitionMap is no longer null?

Correct.

Thread B returns fieldDefinitionMap collection (which was just created by Thread A) and this collection is then immediately 'used by some client' even before Thread A has finished populating this collection.

As a result the collection doesn't include all fields yet (until Thread A will finish populating it) at the time it is already being used and this result in missing columns. 

I have seen this error. It is very rare and hard to reproduce.

**Comment by mythz** [comment]
Semantically still don't see how Thread B (who's waiting on the lock) can return an initialized but non populated collection since they're both done by Thread A within the lock. But if you've observed it than I guess it's possible for double-checked locking to be susceptible to subtle memory model race conditions when checking against 2 variables so I just changed it to wrap everything in a lock in this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/b1d2c93ad0b34c8239e026e422bdc6427850b247
