### ISSUE TITLE
SOAP metadata issue.

### ISSUE THREAD

**Issue by dmytro-gokun** [ServiceStack/Issues#326]
This happened after updating ServiceStack to 4.0.42. SOAP metadata generated are not complete. They only contain request & response types, but not any other types which are used by request & response types. This is a critical issue for us, as many of our customers use the SOAP endpoint.

The easiest way to reproduce is this:
- Create a self-hosted service as described here: https://github.com/ServiceStack/ServiceStack/wiki/Self-hosting

- Change the request type to refer to another type:

```
        public class Person
        {
            public string FirstName { get; set; }
            public string LastName { get; set; }
        }

        [Route("/hello/{Name}")]
        public class Hello
        {
            public Person Person { get; set; }
        }

        public class HelloResponse
        {
            public string Result { get; set; }
        }

        public class HelloService : Service
        {
            public object Any(Hello request)
            {
                return new HelloResponse {Result = "Hello, " + request.Person.FirstName + " " + request.Person.LastName};
            }
        }

```

- Navigate to the SOAP metadata page (http://localhost:1337/soap11). As you can see, there is no definition for the Person class in WSDL.

This used to work properly with with ServiceStack 4.0.40

**Comment by mythz** [comment]
Hi the SOAP WSDLs/XSDs [require DataContract/DataMember attributes on DTO's](https://github.com/ServiceStack/ServiceStack/wiki/SOAP-support#soap--rest). 

So this will work after adding Data Contract attributes, i.e:

```csharp
[DataContract]
public class Person
{
    [DataMember]
    public string FirstName { get; set; }
    [DataMember]
    public string LastName { get; set; }
}

[Route("/hello")]
[DataContract]
public class Hello
{
    [DataMember]
    public Person Person { get; set; }
}

[DataContract]
public class HelloResponse
{
    [DataMember]
    public string Result { get; set; }
}
```

Can you try this and confirms that it works?

**Comment by dmytro-gokun** [comment]
Hi Demis,

thanks for a prompt reply. I've tried adding this attributes and that helped. BUT. The only reason i did not have them in this sample was that it was copied from https://github.com/ServiceStack/ServiceStack/wiki/Self-hosting (and there are no attributes in that sample). In our production we DO have all this attributes specified. And it all worked properly with version ServiceStack 4.0.40. So, i probably have to investigate more and try to isolate what actually causes issue here. Unless you have another quick idea :) (may be you know what exact change in 4.0.42 might have caused this?).

Dmitry.

**Comment by mythz** [comment]
We've added finer-grain controls for controlling which types are exported in the WSDL since Customers were frequently running into issues exporting incompatible types.

You can control which operations and types are exported in the WSDL/XSD's by overriding `ExportSoapOperationTypes()` and `ExportSoapType()` methods in your AppHost, here are the default impls which can be overridden:

```csharp
public virtual List<Type> ExportSoapOperationTypes(List<Type> operationTypes)
{
    var types = operationTypes
        .Where(x => !x.AllAttributes<ExcludeAttribute>()
                    .Any(attr => attr.Feature.HasFlag(Feature.Soap)))
        .Where(x => !x.IsGenericTypeDefinition())
        .ToList();
    return types;
}

public virtual bool ExportSoapType(Type type)
{
    return !type.IsGenericTypeDefinition() && 
            !type.AllAttributes<ExcludeAttribute>()
                .Any(attr => attr.Feature.HasFlag(Feature.Soap));
}
```

The behavior have also changed from trying to export every type to now only the types that are referenced from any of the types returned in `ExportSoapOperationTypes()`. 

If you can let me know of any problematic DTO's I can test them to see if I can repro the issue.

**Comment by dmytro-gokun** [comment]
Okay, so I've done some more investigation on this issue and it looks like i found something.

But let me explain first how I've ran into the problem on the first place:
1. We have a service running that was originally built using ServiceStack 4.0.40 with SOAP enabled.
2. I've updated the service to use ServiceStack 4.0.42 and published it.
3. When clients call the service, i see an exception on the server:

System.AggregateException: One or more errors occurred. ---> System.Runtime.Serialization.SerializationException: 3) Error trying to deserialize requestType: Trackunit.API.GetUnit, xml body: <GetUnit xmlns="http://schemas.servicestack.net/types" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><CategoryId i:nil="true" /><ClientId i:nil="true" /><GroupId i:nil="true" /><Id i:nil="true" /><Point i:nil="true" /><PointId i:nil="true" /><Radius i:nil="true" /><ReferenceNumber i:nil="true" /><SerialNumber i:nil="true" /><ZoneId i:nil="true" /></GetUnit> ---> System.NullReferenceException: Object reference not set to an instance of an object. 
at ServiceStack.Host.Handlers.SoapHandler.ExecuteMessage(Message message, RequestAttributes requestAttributes, IRequest httpReq, IResponse httpRes) 
--- End of inner exception stack trace --- 
at ServiceStack.Host.Handlers.SoapHandler.ExecuteMessage(Message message, RequestAttributes requestAttributes, IRequest httpReq, IResponse httpRes) 
at ServiceStack.Host.Handlers.SoapHandler.Send(Message requestMsg, IRequest httpRequest, IResponse httpResponse) 
at ServiceStack.Host.Handlers.Soap12MessageReplyHttpHandler.ProcessRequest(IRequest httpReq, IResponse httpRes, String operationName) 
at ServiceStack.Host.Handlers.HttpAsyncTaskHandler.<>c__DisplayClass1.<CreateProcessRequestTask>b__0() 
at System.Threading.Tasks.Task.InnerInvoke() 
at System.Threading.Tasks.Task.Execute() 
--- End of inner exception stack trace --- 
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) 
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken) 
at ServiceStack.Host.Handlers.HttpAsyncTaskHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) 
at System.Web.HttpApplication.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) 
---> (Inner Exception #0) System.Runtime.Serialization.SerializationException: 3) Error trying to deserialize requestType: Trackunit.API.GetUnit, xml body: <GetUnit xmlns="http://schemas.servicestack.net/types" xmlns:i="http://www.w3.org/2001/XMLSchema-instance"><CategoryId i:nil="true" /><ClientId i:nil="true" /><GroupId i:nil="true" /><Id i:nil="true" /><Point i:nil="true" /><PointId i:nil="true" /><Radius i:nil="true" /><ReferenceNumber i:nil="true" /><SerialNumber i:nil="true" /><ZoneId i:nil="true" /></GetUnit> ---> System.NullReferenceException: Object reference not set to an instance of an object. 
at ServiceStack.Host.Handlers.SoapHandler.ExecuteMessage(Message message, RequestAttributes requestAttributes, IRequest httpReq, IResponse httpRes) 
--- End of inner exception stack trace --- 
at ServiceStack.Host.Handlers.SoapHandler.ExecuteMessage(Message message, RequestAttributes requestAttributes, IRequest httpReq, IResponse httpRes) 
at ServiceStack.Host.Handlers.SoapHandler.Send(Message requestMsg, IRequest httpRequest, IResponse httpResponse) 
at ServiceStack.Host.Handlers.Soap12MessageReplyHttpHandler.ProcessRequest(IRequest httpReq, IResponse httpRes, String operationName) 
at ServiceStack.Host.Handlers.HttpAsyncTaskHandler.<>c__DisplayClass1.<CreateProcessRequestTask>b__0() 
at System.Threading.Tasks.Task.InnerInvoke() 
at System.Threading.Tasks.Task.Execute()<--- 

In our code we have these lines:

private const Feature EnabledFeatures = Feature.Soap | Feature.Metadata | Feature.PredefinedRoutes | Feature.RequestInfo | Feature.Json | Feature.Xml | Feature.Html;
        
public override void Configure(Container container)
{
   /// ,,,,
   Config.EnableFeatures = EnabledFeatures;
   /// ,,,,
}

So what i've found is this: once i add Feature.Csv to EnabledFeatures, existing clients start to work with new service (one built with 4.0.42). I've failed to build a distilled sample so far, but i will continue trying if it's needed.

Do you have any idea why Feature.Csv changes this behavior?

**Comment by mythz** [comment]
Nope I can't see why `Feature.Csv` would have any impact. Although note the API for specifying configuration is `SetConfig()`, e.g:

```csharp
SetConfig(new HostConfig {
    EnableFeatures = EnabledFeatures
});
```

But the real exception is getting wrapped under an async `AggregateException`, hiding the inner exception. Can you try calling a sync version of the Service and publishing the StackTrace?

**Comment by dmytro-gokun** [comment]
Actually there is the inner exception's info:

```
System.Runtime.Serialization.SerializationException: 3) Error trying to deserialize requestType: Trackunit.API.GetUnit, xml body:
```

Also, i'm not quite sure if i understand this: "Can you try calling a sync version of the Service". Can you advise how i do that? (NB: the exception above is captured & logged on the server, not on a client).

**Comment by mythz** [comment]
ok nvm I thought the `AggregateException` was due to calling an Async Service impl, but it looks like it's because its being logged at the outer `HttpAsyncTaskHandler` layer.

I need a repro or to see the exact StackTrace/code causing it. Can you register a `UncaughtExceptionHandlers` and `ServiceExceptionHandlers` handlers in your AppHost which logs the StackTrace of the Exception. Also don't forget to change over to use the `SetConfig()` API.

**Comment by dmytro-gokun** [comment]
The exception you see above is logged from Global.Application_Error like this:

```
Log.Error(Request, Server.GetLastError());
```

We also log another exception from ServiceExceptionHandlers:

```
System.NullReferenceException: Object reference not set to an instance of an object. 
at ServiceStack.Host.Handlers.SoapHandler.ExecuteMessage(Message message, RequestAttributes requestAttributes, IRequest httpReq, IResponse httpRes)
```

There is no further exception stack trace from ServiceStack's guts.

May be the reason i can not reproduce it in a fresh project is that i'm using a self-hosted service here unlike the real app which uses IIS for hosting. I'm not quite sure. But, somehow adding Feature.Csv fixes the issue immediately (i'm using SetConfig now, does not make any difference).

Anyways, i will try to build a repro. It's just quite hard to do cause i have this old client code which uses a Service Reference to the prev version of the service etc.

**Comment by mythz** [comment]
Can you post the Raw HTTP traffic, e.g. using Fiddler. Also please provide the class Definition for `GetUnit` Request DTO and its Response DTO (if any). Maybe I can try reproducing the issue from my side.

**Comment by dmytro-gokun** [comment]
So, i was finnaly able to reproduce the bug. It looks like Request.ReturnAuthRequired() & Feature.Csv are bound in some mysterious way.

Here is the repro: https://dl.dropboxusercontent.com/u/89760017/ServiceStackBug.zip

If you comment out SetConfig call in AppHost.cs, everything works as expected (and as it used to with 4.0.40).

**Comment by mythz** [comment]
Firstly you should ideally only be short-circuiting the Request like this in a Request Filter, e.g:

```csharp
GlobalRequestFilters.Add((req, res, dto) =>
{
    var auth = req.GetBasicAuthUserAndPassword();
    if (auth == null || auth.Value.Key != "User" || auth.Value.Value != "Password")
        res.ReturnAuthRequired();
});
```

Where anything that ends the Response like `res.ReturnAuthRequired()` will short-circuit the Response

But the issue is that you shouldn't return `null` in a SOAP Service which expects a strong-typed Response DTO back as per its WSDL contract, so you can return an empty DTO or preferably a Response DTO with the Error info populated, e.g:

```csharp
return new HelloResponse {
    ResponseStatus = new ResponseStatus { ErrorCode = "Authentication Required" }
};
```

The issue happens when you have a Global Request Filter which [CSV Format Registers](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/Formats/CsvFormat.cs#L16) and it tries to look up which Response Filters to execute based on the type of the response dto which is `null` here. 

I've now added fix the NRE but you shouldn't return `null` in SOAP Services you can instead throw an Exception, at which point your Response DTO should have a `ResponseStatus` property to capture the error information.

**Comment by dmytro-gokun** [comment]
Thanks a lot for this finding!

It is a bit confusing though that it worked fine with SOAP before and still works fine with JSON/XML :).

Anyways, i've changed my code to:

```
            var auth = Request.GetBasicAuthUserAndPassword();
            if (auth == null || auth.Value.Key != "User" || auth.Value.Value != "Password")
            {
                Response.ReturnAuthRequired();
                return new HelloResponse();
            }
```

and it works just fine! Do you think this code is okay (i've omitted ResponseStatus population for the sake of brevity)?

**Comment by mythz** [comment]
IMO it's poor form to short-circuit Requests inside a Service, ideally a Service should either return a successful response, throw a C# Exception or return a customized `HttpResult` or throw a `HttpError` to customize the HTTP Response. 

I'd only return null for Services that don't have a response but even in this case I'd just have a `void` method with the Request DTO implementing `IReturnVoid` to signal this intent - which incidentally gets converted to a `204 No Content` HTTP Response. But for SOAP Services I would always return the expected Response DTO or throw an Exception.

I would only call anything that short-circuits the Request, i.e. calls `IResponse.EndRequest()` in filters which has the effect of short-circuiting the Request Pipeline and writing the Response immediately - Whilst it works IMO it's confusing to do this inside a Service.

But for Basic Auth in particular I would just register `BasicAuthProvider` which is purpose built for validating HTTP Basic Auth. If you don't want to validate against a static Username/Password (i.e. instead of User/Pass in UserAuth tables) then I'd just be using a Custom BasicAuthProvider that inherits [BasicAuthProvider](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/Auth/BasicAuthProvider.cs) and overrides `TryAuthenticate`.

**Comment by dmytro-gokun** [comment]
Thanks a lot of for your answer!

I agree that it is was a bad idea to return null here.
Ideally, i would prefer to throw an HttpError and that's what i tried at first run. Problem is that not only i have to return 401, but also to set "WWW-Authenticate" header (otherwise, browsers & SOAP client libraries do no handle 401 properly). And that header gets lost when an HttpError is thrown from the service. That is the main problem. May be there is a solution for that?

About using Custom BasicAuthProvider. It must be the correct solution to the problem. But when i tried it back then, i had hard time to customize it for our purposes. May be i have to revisit it.

**Comment by mythz** [comment]
You can customize the `Headers` Dictionary when returning a `HttpResult` or throwing a `HttpError` to modify the returned HTTP Headers.
