### ISSUE TITLE
API version not displaying anymore in Swagger-UI

### ISSUE THREAD

**Issue by DJFliX** [ServiceStack/Issues#333]
When I create an empty ASP.NET project and put the following in the Configure function:

            SetConfig(new HostConfig
            {
                ApiVersion = "0.2.0"
            });
            this.Plugins.Add(new SwaggerFeature());

I expect to see the version of the API at the bottom of the Swagger-Ui page (next to "Base URL:"). In versions before 4.0.40 (i believe) this worked. On every version after this seems broken.

**Comment by mythz** [comment]
This appeared to be an issue with the upstream swagger-ui project not handling the existing Swagger 1.2 spec properly, should now be fixed with this commit: https://github.com/ServiceStack/ServiceStack/commit/6245cd4f367f1b2de31c529bfd653a8b7c66ecdc

This change is available from v4.0.43+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by DJFliX** [comment]
Great, thanks a lot! I'll test it first thing in the morning when I'm at
work!

**Comment by DJFliX** [comment]
Works perfectly! Thanks a lot!

**Comment by mythz** [comment]
Cool, thx for the update :)
