### ISSUE TITLE
Swagger duplicating fields, not showing post request model schema

### ISSUE THREAD

**Issue by mjdaly** [ServiceStack/Issues#341]
https://drive.google.com/file/d/0B5cglv2mrbC7Wjl4a3lieXRmd2s/view?usp=sharing

In the linked project, Swagger UI seems to behaving incorrectly.
* Between versions 4.0.40.0 and 4.0.43.0, the POST request model schema is no longer filled in on routes
 * /hello
 * /hello2
* Fields are being duplicated on routes
 * /hello/{Required1}/{Optional1}
 * /hello2/{Required1}/{Required2}/{Optional1}

**Comment by mythz** [comment]
Can you post a screenshot highlighting the issue I'm not seeing it?

**Comment by mjdaly** [comment]
<img width="531" alt="swaggerbugs" src="https://cloud.githubusercontent.com/assets/2940965/9557966/4dbcf2c8-4dd8-11e5-8765-dc5dec556421.PNG">

**Comment by mjdaly** [comment]
Sure

**Comment by mythz** [comment]
ok thx for the screenshot thought the issue was in v4.0.40 as well which is why I couldn't see it. 

Should now be fixed with this commit: https://github.com/ServiceStack/ServiceStack/commit/147a878ccf6f7a105066ef42f715c5aa7b334b40

This change is available from v4.0.43 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

Let me know if there are any remaining issues.
