### ISSUE TITLE
getting DtoUtils service exception notice in logs, no detail tho

### ISSUE THREAD

**Issue by ericpeterson87** [ServiceStack/Issues#347]
i updated to the 4.0.44.0 release recently and now I am seeing these quite a bit in my logs:

2015-09-02 15:17:04.3667 | Error | DtoUtils | ServiceBase<TRequest>::Service Exception 

how do i know what actually failed? i dont recall ever seeing that before

i tried adding the handlers per this link:

https://github.com/ServiceStack/ServiceStack/wiki/Error-Handling#register-handlers-for-handling-service-and-non-service-exceptions

but then after a while SS would throw a 503 and nothing would fix it short of a reboot of the IIS box. Commenting out those 2 things fixed things. all i added was a call to nlog to log the error.

i also get this a lot:

2015-09-02 15:19:47.4530 | Error | RedisNativeClient | Unable to Connect: sPort: 0 

both on a hyper-v host and a dedicated server. connected clients on redis is usually in around 6 but can go into the 50s some times. the dedicated host is running redis 3.03 and the hyperv host is running 2.8x

i am using a timeout value of 1000 in my web.config

redis config is all defaults running on ubuntu.

i tried switching to the dedicated hardware as i saw some issues about latency on hyper-v instances.

i kicked nlog config to Debug mode and will let it run overnight to see if anything else jumps out of the logs

ps this is on windows 2012R2 stock as well

Thanks!

**Comment by mythz** [comment]
The error message is [being logged in DtoUtils](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/DtoUtils.cs#L157) and gets passed the full Exception:

    Log.Error("ServiceBase<TRequest>::Service Exception", ex);

Which is delegated to the Logging Provider to log, but I've just noticed that a recent refactor to preserve callsites in NLog wasn't calling the right overloaded method which is [now fixed in this commit](https://github.com/ServiceStack/ServiceStack/commit/60a32fb91db934fd94bddbdb4bb6f422529ccf64).

You can [upgrade to v4.0.45 on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet) or copy and use the [NLogFactory](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Logging.NLog/NLogFactory.cs) and [NLogLogger](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Logging.NLog/NLogLogger.cs) classes to get the fix so the exception gets properly logged to NLog. Could you update NLog, then let me know what the Exceptions are?

Since the exception is being thrown in a Service you'd only [need to register a ServiceExceptionHandlers](https://github.com/ServiceStack/ServiceStack/wiki/Error-Handling#register-handlers-for-handling-service-and-non-service-exceptions) to be able to handle the Exception. I couldn't guess why it would result in a 503, although "503 Service Unavailable" errors aren't thrown by ServiceStack, they'd be thrown by the web server/IIS, perhaps due to a StackOverflow, deadlock, unhandled async exception, etc.

"Unable to Connect" means it was unable to establish a TCP Socket Exception with the redis instance, maybe due to an overloaded Redis Server, unreliable network, etc.

**Comment by ericpeterson87** [comment]
OK i will do this as soon as i can. 

when you say "update nlog" i assume you mean the nlog SS piece?

also, can you bump the version of nlog to 4.1 in SS? i updated that as well but had to downgrade as things went sideways when i deployed

**Comment by mythz** [comment]
Hi, I already bumped to use NLog to v4.1.0 in the above commit. Yes, just the SS NLog adapter.

**Comment by ericpeterson87** [comment]
This is working great! I see the exception details now. it was from validation.validationError

many thanks!

**Comment by mythz** [comment]
Great, glad to hear it!
