### ISSUE TITLE
JsConfig.IncludeNullValues breaks Swagger

### ISSUE THREAD

**Issue by AVee** [ServiceStack/Issues#362]
I've got one project which has JsConfig.IncludeNullValues = true set and I noticed this breaks the  Swagger-UI. The /resource/* json will include all the null values which breaks swagger-client.js which expects things to be undefined, and not null. 

It's a minor use with a clear workaround, so it's not urgent for us. But I thought I'd report it anyway...

**Comment by mythz** [comment]
This is an annoying one since we don't control the Swagger libs and don't want to maintain our own fork just to support non-standard defaults.

To get around this I've [added a new ReuseScope](https://github.com/ServiceStack/ServiceStack/commit/dd4a23e37e43cf82374511a94bb1e09cdcfafaa5) feature which will allow specifying a custom Config Scope for adhoc Services by decorating the response DTO with a `HttpResult` that contains custom configuration to explicitly specify JsConfig options which [Swagger Responses are now using](https://github.com/ServiceStack/ServiceStack/commit/7dd3adf1f8c7a71bb50a5fe02313b0b63136ade2) to override any `JsConfig.IncludeNullValues` back to its default, e.g:

```csharp
return new HttpResult(result) {
    ResultScope = () => JsConfig.With(includeNullValues: false)
};
```

This change is available from v4.0.47+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
