### ISSUE TITLE
Returning interface (instead of concrete) types from endpoints causes Typescript code generation to fail

### ISSUE THREAD

**Issue by bumblebeeman** [ServiceStack/Issues#365]
I am not sure if this is a bug or a feature.

Basically if I return, for example, a List<T> from an endpoint, the typescript generation works fine, but if I change this to an IList<T> it no longer compiles.

I notice in **TypeScriptGenerator.cs**, you have a dictionary called *TypeAliases*, *List<T>* is in this dictionary but *IList<T>* is not.

Is it recommended to not return interface types from endpoints with ServiceStack, or could this be resolved by potentially updating the *TypeAliases* dictionary?

Thanks

**Comment by mythz** [comment]
You should [never return interfaces in DTOs](http://stackoverflow.com/a/10759250/85785) interfaces add coupling across process boundaries and are not supported by all serializers. IList is especially useless since its almost always hiding a concrete List.

It's use should be discouraged so I want to avoid anything that supports their use.

**Comment by bumblebeeman** [comment]
Ok thanks for clarifying!
