### ISSUE TITLE
Xamarin.Mac needs its own PCL export provider

### ISSUE THREAD

**Issue by NateRickard** [ServiceStack/Issues#366]
Related discussion [here](http://stackoverflow.com/questions/28725867/servicestack-client-on-xamarin-mac-not-ios)

To recap my comment there a bit:

The suggestion in the answer there to use the the IosPclExportClient appears to work in 'debug' mode.  However, when you build for release or enable SDK linking directly in the build settings, the compiler will link away (remove) the Xamarin.iOS assembly that the IosPclExportClient depends on, resulting in the following compile error:

>Error MM2002: Failed to resolve assembly: 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' (MM2002)

So it would seem that Xamarin.Mac requires its own PCL export client with a reference to Xamarin.Mac rather than Xamarin.iOS.

I see there is a ServiceStack.Pcl.Mac20 project in the SS repo & Xamarin solution - is this something that's already being rectified for a future release?

**Comment by NateRickard** [comment]
Closing, reopened with license holder acct

**Comment by mythz** [comment]
@NateRickard FYI this issue is being tracked here: https://github.com/ServiceStack/Issues/issues/367#issuecomment-151629243

The ServiceStack.Pcl.Mac20 is now directly referencing Xamarin.Mac which now needs to be configured with: 

```csharp
ServiceStack.MacPclExportClient.Configure();
```

This change is available from the v4.047 pre-release NuGet builds which are [now on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
