### ISSUE TITLE
JsonSerializer fails to deserialize 'null' value into HashSet

### ISSUE THREAD

**Issue by marko444** [ServiceStack/Issues#381]
Following test throws exception with this message: : Failed to set property 'set' with ''

```C#
        [DataContract]
        public class ClassWithNestedHashSet
        {
            [DataMember(Name = "set")]
            public HashSet<string> Set { get; set; }
        }

        [Test]
        public void Can_deserialize_null_Nested_HashSet()
        {
            JsConfig.ThrowOnDeserializationError = true;
            string json = @"{""set"":null}";
            var o = json.FromJson<ClassWithNestedHashSet>();
            Assert.That(o.Set, Is.Null);

            JsConfig.Reset();
        }
```

**Comment by mythz** [comment]
Cheers, thx for the repro. Should be now fixed with this commit: https://github.com/ServiceStack/ServiceStack.Text/commit/57a26a9b0749baf7e805b165482f6af2af05b774

This fix is available from v4.0.51 that's [now on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

FYI deserializing properties is case-insensitive so there's no need for the `[DataMember]` alias.
