### ISSUE TITLE
RemoveByPattern method is not available

### ISSUE THREAD

**Issue by sdevvathi** [ServiceStack/Issues#385]
Hi,

I'am facing the following issue with ServiceStack PooledRedisClientManager() in my C#.net application.
--> RemoveByPattern() method is not avaliable.

Before we are using the RedisClient() and we are able to get the method. Could you please help out  there is any alternate method is available in PooledRedisClientManager for RemoveByPattern?

Regards,
Suresh

**Comment by Layoric** [comment]
The extension method `RemoveByPattern` off `ICacheClient` is not available from a `PooledRedisClientManager` because it's a manager of cache clients not a client itself. 

You'll want to get a client instance from the `PooledRedisClientManager` by calling `GetClient()`.

For future reference, these kinds of questions are better suited to our [customer forums](https://forums.servicestack.net/) or a [StackOverflow question](https://stackoverflow.com/) using the `ServiceStack` tag rather than GitHub issues which is suited for bug reports.

Thanks! :+1:
