### ISSUE TITLE
Why is SqlExpression<T>.OrderByDescending(string orderBy) method is missing?

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#397]
This signature exists for SqlExpression<T>.OrderBy(string orderBy) but not for descending method.
Is it a forgetting?

**Comment by mythz** [comment]
Well since the `OrderBy()` takes a string you could already do:

    .OrderBy("field DESC");

Anyway I've added it now in this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/c56a5dfda5513f2b3feca82f66c2bb8f52ae0d14

This change is available from v4.0.53 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet)

**Comment by jklemmack** [comment]
Man - this one occasionally bugged me, but I never enough to raise it as an issue.  Regardless - thanks!

**Comment by labilbe** [comment]
Thank you very much Demis!
