### ISSUE TITLE
ServiceStack Android Studio 2.0 Plugin Error

### ISSUE THREAD

**Issue by doaji** [ServiceStack/Issues#422]
Hey guys,

I recently updated my android studio to 2.0. When i open it i get an error from the servicestack plugin:

Plugin Error
           Problems found loading plugins:
           Plugin "ServiceStack" was not loaded: required plugin "org.jetbrains.idea.maven" not installed.
           Disable ServiceStack
           Open plugin manager

What could be wrong here?

Stats:
OS: Windows 7
IDE: Android Studio 2.0
Plugin Version: 1.0.8

Thanks in anticipation. and GREAT WORK, i just started using ServiceStack (i have been a life long WCF user) and it is amazing.

**Comment by mythz** [comment]
@Layoric please have a look when you can

**Comment by Layoric** [comment]
Hi @doaji ,

Looks like the newly released Android Studio 2.0 broke some dependencies. I've published a fix for this issue and should be available shortly from within Android Studio. 

If you're keen to get this fixed ASAP, you can add the nightly plugin repository for the plugin by the following steps.

- Open `Settings` in Android Studio from the File menu
- Go to Plugins
- Click on **Browse repositories**
- Then click **Manage repositories**
![image](https://cloud.githubusercontent.com/assets/234642/14457621/1c327802-00ef-11e6-9cc6-0d21b81025be.png)

- Click the green add button and provide the url - `https://plugins.jetbrains.com/plugins/nightly/7749`
![image](https://cloud.githubusercontent.com/assets/234642/14457642/3f061ff0-00ef-11e6-9b79-1037b2abdf59.png)

- Click OK

You should then see version 1.0.9 appear which includes the fix for Android Studio 2.0.

Update here and let me know how you go :+1:

**Comment by doaji** [comment]
I was able to update the plugin and everything works fine now. Thanks guys.

**Comment by mythz** [comment]
perfect, glad to hear it :+1:
