### ISSUE TITLE
JsonServiceClient & 100% CPU usage

### ISSUE THREAD

**Issue by dmytro-gokun** [ServiceStack/Issues#437]
We have an application which uses JsonServiceClient to call into another ServiceStack application.
The call happens asynchronously, using JsonServiceClient's GetAsync() method. Typically, 300-400 requests/sec happen. Mostly, the application runs fine. Normal CPU usage by the app is 10-20%. However, sometimes (several times a day, no particular pattern) we see sudden CPU peaks which may last for dozens of minutes. Restarting the application helps immediately. Sometimes, the CPU usage goes to the normal without restart.

I'm trying to profile the application to see what happens. I use PerfView for that. I see that during the CPU peaks, the CPU usage is evenly contributed between 3 methods:

System.Threading.Timer..ctor()
System.Threading.Timer.Dispose()
System.Threading.TimerQueueTimer.Change()

All these methods are called from AsyncState.StartTimer & AsyncState.HandleSuccess. They are competing on some internal timer queue lock.

So, I'm not sure if it's ServiceStack problem or not. Do you have any thoughts?

Another thing. Do not you think that using timers to handle HTTP timeouts is a good idea. Might it make more sense to use a CancellationTokenSource with a timeout and then link it to the CancellationToken with CreateLinkedTokenSource? This way, all use of timer is the async code is avoided.

**Comment by dmytro-gokun** [comment]
Just came to think about this ... We use a singleton instance of JsonServiceClient here.Is it okay (cookies are not used)?

**Comment by mythz** [comment]
I don't see an alternative to handling timeouts on async requests with `HttpWebRequest` other than using a Timer to abort the request, which is what the impl is currently doing. I've just added a new option where you can switch off the Timer with:

```csharp
AsyncServiceClient.DisableTimer = true;
```

Effectively this means your async Requests wont have any client timeout and would have to rely on your Server Request Timeout in order to terminate long running requests. This option is now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

Otherwise using Sync requests wouldn't have this problem, the alternative is to use the [HttpClient-based JsonHttpClient](https://github.com/ServiceStack/ServiceStack/wiki/C%23-client#jsonhttpclient) which doesn't need a timer.

Using a singleton Service Client should be ok since there's nothing mutable other than the CookieContainer is shared between requests, also HttpWebRequest is pooled under the covers so there shouldn't be a noticeable difference between reusing a singleton instance or using new JsonServiceClient instances as either way a new HttpWebRequest is created for each request.

So the options to avoid the Timer is to disable it with the flag above, switch to JsonHttpClient or use sync requests.

**Comment by dmytro-gokun** [comment]
I was not aware of JsonHttpClient for some reason, missed it somehow. Thanks for pointing it out, i will give it a try (Y). Is it thread-safe as well?

**Comment by mythz** [comment]
Yeah it's [designed to be reused](https://blogs.msdn.microsoft.com/henrikn/2012/08/07/httpclient-httpclienthandler-and-webrequesthandler-explained/):

> A single HttpClient can be used to send as many HTTP requests as you want concurrently so in many scenarios you can just create one HttpClient and then use that for all your requests.
