### ISSUE TITLE
When use Twemproxy,Servicestack.Redis GetServerRole Throw ex

### ISSUE THREAD

**Issue by hgp7369** [ServiceStack/Issues#456]
![image](https://cloud.githubusercontent.com/assets/1761858/16612672/bd366f0e-439a-11e6-8048-22a47b77a0f2.png)
when connect twemproxy, not support **ROLE**
`AssertServerVersionNumber()` return -1,and `this.Info` is null
so `this.Info.TryGetValue("role", out role);` will throw ex 

> Zero length response

**Comment by xplicit** [comment]
twemproxy does not support redis `INFO` nor `ROLE` commands. ServiceStack.Redis got `ServerVersionNumber` and `Role` by parsing results of `INFO` command and because twemproxy does not return any data for INFO you get described behaviour. 

You can see the list of supported redis commands by twemproxy here https://github.com/twitter/twemproxy/blob/master/notes/redis.md

**Comment by hgp7369** [comment]
you can try it,there is some error in the code
