### ISSUE TITLE
debuglogger can't work

### ISSUE THREAD

**Issue by gitlsl** [ServiceStack/Issues#459]
I set   LogManager.LogFactory = new DebugLogFactory(); but it can't work(no output)
I decompile（resharper)  see the code is 

```csharp 
private static void Log(object message, Exception exception)
{
      string str1 = message == null ? string.Empty : message.ToString();
      if (exception == null)
          return;
      string str2 = str1 + ", Exception: " + exception.Message;
}
```

but at source is 

```csharp 
private static void Log(object message, Exception exception)
{
    string msg = message == null ? string.Empty : message.ToString();
    if (exception != null)
    {
        msg += ", Exception: " + exception.Message;
    }
    System.Diagnostics.Debug.WriteLine(msg);
}
```

**Comment by mythz** [comment]
Yeah it's only for when ServiceStack is compiled in Debug mode since it's automatically gets stripped by the compiler in release builds, so it's only useful if you use Debug builds of ServiceStack. 

You can take a copy of the Debug Logger and copy into your own project, i.e:

  - [DebugLogFactory.cs](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Common/Logging/DebugLogFactory.cs)
  - [DebugLogger.cs](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Common/Logging/DebugLogger.cs)

Otherwise you'll need to use one of the other [Logging Providers](https://github.com/ServiceStack/ServiceStack/wiki/Logging) like `ConsoleLogFactory`.
