### ISSUE TITLE
Expression evaluation issue in OrmLite

### ISSUE THREAD

**Issue by dylanvdmerwe** [ServiceStack/Issues#484]
With reference to [this](https://forums.servicestack.net/t/sqlexpression-not-being-parsed-correctly/2922) forum post. 

See attached example repo.

The problem is that the `env` variable is being evaluated but not the cast. This does not work:
```
var env = DeployedEnvironment.Development;
Expression<Func<ActivityLog, bool>> expression = x => !x.IsDeleted && x.Environment == (byte) env;
var list = Db.Select<ActivityLog>(expression);
```

Which means that something like this also does not work:
```
Expression<Func<ActivityLog, bool>> expression = x => !x.IsDeleted && x.Environment == (byte) DeployedEnvironment.GetEnvironment();
var list = Db.Select<ActivityLog>(expression);
```

This does work however when casting directly on an enum (and not a variable):
```
Expression<Func<ActivityLog, bool>> expression = x => !x.IsDeleted && x.Environment == (byte)DeployedEnvironment.Development;
var list = Db.Select<ActivityLog>(expression);
```

Tested using version 4.5.0.

[WebApplication1.zip](https://github.com/ServiceStack/Issues/files/478059/WebApplication1.zip)

**Comment by mythz** [comment]
Hey Dylan, as I [mentioned in the forums](https://forums.servicestack.net/t/sqlexpression-not-being-parsed-correctly/2922/2?u=mythz) enums need to be annotated with either `[Flags]` or `[EnumAsInt]` in order for the Enum to be treated as an integer, otherwise it's passed in the db param as a string and the query wont match the `byte` field it's stored as.
