### ISSUE TITLE
The transaction is either not associated with the current connection or has been completed.

### ISSUE THREAD

**Issue by Savvkin** [ServiceStack/Issues#506]
Hello. I have a service, that calls method like this from tens of threads:
```C#
public static void Foo()
{
  using(var conn = connString.OpenDbConnection())
  {
    var id = (int)conn.Insert(objA, selectIdentity: true);
    objA.Id = id;
    objB.Name = objA.Name;
    conn.Update(objB);
  }
}
```

Sometimes (especially at launch, when multiple threads trying to call the same method at the same time) my app crashes with this exception:
```
System.InvalidOperationException: The transaction is either not associated with the current connection or has been completed.
  at System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
  at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
  at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
  at ServiceStack.OrmLite.OrmLiteWriteCommandExtensions.Update[T](IDbCommand dbCmd, T obj)
  at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)
.....
```

Error says about transactions, but as you can see, I don't use any transactions. So it happens somewhere inside ServiceStack.OrmLite.

**Comment by mythz** [comment]
I'm going to need to be able to repro this in order to tell what's going wrong, I've tried to create a multi-threaded test to try repro the issue from your example in [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/a9375d9aa6b4161e9ba7e3fb4b3e2c1d94103ec7):

```csharp
[Explicit]
public class MultiThreadedUpdateTransactionIssue : OrmLiteTestBase
{
    public class ModelWithIdAndName
    {
        [AutoIncrement]
        public int Id { get; set; }
        public string Name { get; set; }
    }

    [Test]
    public void Can_Insert_Update_record_across_multiple_threads()
    {
        using (var db = OpenDbConnection())
        {
            db.DropAndCreateTable<ModelWithIdAndName>();
        }

        int count = 0;

        20.Times(i =>
        {
            ThreadPool.QueueUserWorkItem(state =>
            {
                40.Times(_ =>
                {
                    using (var db = OpenDbConnection())
                    {
                        var objA = new ModelWithIdAndName { Name = "A" };
                        var objB = new ModelWithIdAndName { Name = "B" };

                        objA.Id = (int)db.Insert(objA, selectIdentity: true);

                        objB.Id = (int)db.Insert(objB, selectIdentity: true);
                        objB.Name = objA.Name;

                        db.Update(objB);
                        Interlocked.Increment(ref count);
                    }
                });
            });
        });

        Thread.Sleep(5000);
        Assert.That(count, Is.EqualTo(20 * 40));
    }
}
```

But this passes without issue over multiple runs. Can you please modify the above test (or paste in Console App) to reproduce the error, please also include the full StackTrace and the RDBMS you're using, thanks.

**Comment by Savvkin** [comment]
Tried to reproduce is in test, no luck. I'm missing some unknown conditions.
Could you look into the code and think of possibilities, how virtually this can happen?

**Comment by mythz** [comment]
I need a [repro to be able to investigate this issue further](https://github.com/ServiceStack/Issues#you-can-view-existing-issues-or-report-a-new-issue) as it's not possible to identify the issue from just the example provided which I'm assuming is incomplete and does not contain the cause of the issue. You likely have different code that's causing the issue which I can't tell if it's being used incorrectly or not without an isolated repro that I can run locally which I'll need in order to be able to resolve this issue.

If you're able to extract a repro from your code please post it here.

**Comment by mythz** [comment]
One thing you should check that could cause this issue is if you're sharing a non-ThreadSafe `IDbConnection` instance among different threads which would lead to a race condition like this. You need to ensure each Thread gets its own `IDbConnection` from the factory.
