### ISSUE TITLE
Metadata generation error when several types with same class name

### ISSUE THREAD

**Issue by haraldv** [ServiceStack/Issues#510]
Error reproduction for metadata page error in ServiceStack 4.5.4

Details in repository.

Repro:
https://github.com/haraldv/SS.MetadataErrorRepro

**Comment by mythz** [comment]
It's because you're using the same names for your DTOs which is [an issue for metadata Services](http://docs.servicestack.net/add-servicestack-reference#limitations):

> ### Limitations
> In order for Add ServiceStack Reference to work consistently across all supported languages without .NET semantic namespaces, DTOs includes an additional restriction where each Type must be uniquely named.

Reusing the same DTO names for your Service Models has several issues since you're relying on C# namespaces for your Services which isn't projected in the metadata Services external clients see which don't understand C# namespace semantics and only see model schemas in Service Contracts. Reusing DTO names also prohibits working them working in [non .NET languages](http://docs.servicestack.net/add-servicestack-reference) since they don't support C# namespace semantics. As it can cause several runtime issues it's highly recommended to use unique names for your DTOs which will solve this issue.

This specific issue here is that the Metadata Service that returns metadata about Service doesn't include the C# namespace for a Types Generic Args and only captures the DTO Name, e.g. `List<HelloDetail>` and since you have multiple DTOs with the same name it's overridden. 

This is a technical limitation for Generic Type Args. The solution is to always using unique Type names in your Service Contract (which also saves you from other runtime issues). I've also [added a commit](https://github.com/ServiceStack/ServiceStack/commit/7c7723d6411d7be5f81c375d54fa50351fcc8548) where using arrays instead, e.g:

```csharp
public class Wrapper
{
    public HelloDetail[] HelloDetails { get; set; }
 }
```

Will be able resolve the correct type as it's able to use the namespace to find a specific match. As Arrays have the same wireformat (in most serializers) as `List<T>` this won't be a breaking change. (i.e. clients sending `List<T>` DTOs will deserialize into `T[]` on the server).

The fix for Arrays is available from v4.5.5 that's now [available on MyGet](http://docs.servicestack.net/myget), but the recommendation is to always use unique names (and not rely on internal C# namespaces) in any Service boundary.
