### ISSUE TITLE
Razor Helpers in external .cshtml Not Supported

### ISSUE THREAD

**Issue by adzy84** [ServiceStack/Issues#515]
It seems that that using razor helpers defined in a separate .cshtml file as described in the section "Reusing @helpers across multiple views" of [this article](https://weblogs.asp.net/scottgu/asp-net-mvc-3-and-the-helper-syntax-within-razor) is not supported with service stack. 

After many hours searching documentation, stackoverflow and previous issues I have not come across a resolution to this. Even digging into the source code doesn't yield any answers other than it is not supported. 

Am I missing something, or is this functionality I'll need to code myself if i need it, or is it likely to be implemented in a future service stack release.

**Comment by mythz** [comment]
You can define a helper in the same source file, but not an external source file. The external helper views is an MVC feature i.e. it's not a Razor feature. You will be able to use MVC features in the .NET Core version of ServiceStack since [ServiceStack's Razor features is a new implementation built on MVC](http://docs.servicestack.net/netcore-razor) so it has access to all MVC's features.

If you want to share functionality across all multiple views you can define an HtmlHelper extension method, e.g:

```csharp
public static class HtmlHelpers
{
    public static MvcHtmlString DisplayPrice(this HtmlHelper html, decimal price)
    {
        return MvcHtmlString.Create(price == 0
            ? "<span>FREE!</span>"
            : $"{price:C2}");
    }
}
```

Which you can then use in your views like:

```html
@Html.DisplayPrice(0)

@Html.DisplayPrice(1.1m)
```
