### ISSUE TITLE
Hashset keys are surrounded with double brackets when inserting Json object using RedisTypedClient

### ISSUE THREAD

**Issue by amirbrb** [ServiceStack/Issues#525]
Hi, 
I noticed that when i insert a value into an hash using RedisTypedClient the key is being "wrapped" with brackets ("Foo" rather than Foo).
When inserting a value using the RedisClient as string the issue does not occur.
Please see attached image and code sample

```
private void Work()
        {
            var key = "Key5";
            var itemKey = "item_" + key;
            var typedItemKey = itemKey + "_t";
            var redisManager = new PooledRedisClientManager(12, "localhost:8740");
            var instance = new Foo()
            {
                TripleFoo = "aaaa",
                DoubleFoo = 2
            };

            using (var client = redisManager.GetClient())
            {
                client.SetEntryInHash(key, itemKey, JsonConvert.SerializeObject(instance));
                client.As<Foo>().SetEntryInHash(client.As<Foo>().GetHash<string>(key), typedItemKey, instance);
            }
        }

        [Serializable]
        private class Foo
        {
            public string TripleFoo { get; set; }
            public int DoubleFoo { get; set; }
        }
```

Please check if there is a solution to this issue. 

![image](https://cloud.githubusercontent.com/assets/9437554/23753877/b6c21d02-04e3-11e7-844d-58ee216db91b.png)

**Comment by mythz** [comment]
Everything is serialized to JSON when using the Redis Typed Client, which is why `Foo` string is serialized with quotes to `"Foo"` as that's what a string in JSON serializes too, e.g [javascript:JSON.stringify("Foo")](javascript:JSON.stringify("Foo")).

Don't mix and match your own Serialization with Redis Typed Client which does it's own serialization. If you want to use your own serialization use the string-based `IRedisClient` (i.e. instead of the Redis Typed Client).

Also you don't need to use `[Serializable]` attribute, it doesn't have any impact in any of our serializers or any 3rd party serializers (i.e. it's only really useful with .NET's BinaryFormatter).
