### ISSUE TITLE
C# client may create multiple connections after exceptions occurred

### ISSUE THREAD

**Issue by hongchenmck** [ServiceStack/Issues#527]
The ServiceStack C# client tries to recover itself by restarting in the event of exception. If there are multiple tasks running, it triggers multiple stop/start on each task which may end up with multiple connections.

**Comment by mythz** [comment]
Hi sorry for the delay, this issue was posted just after we begun our code-base migration to VS2017 which we've just finished completing.

This issue should be resolved with [this commit](https://github.com/ServiceStack/ServiceStack/commit/f3fcf847269adb95e6a04d70836f4d94060f8608) which is now [available on MyGet](http://docs.servicestack.net/myget).
