### ISSUE TITLE
PooledRedisClientManager causes lock contention

### ISSUE THREAD

**Issue by citigodev** [ServiceStack/Issues#534]
We have several of web servers using ServiceStack and connect to a single Redis server with PooledRedisClientManager (all default parameter).

Our production servers sometime has very high cpu usage (almost 100%). We used dottrace to profile and troubleshoot the problem.

Please take a look at the image, looks like there is a problem with ServiceStack Redis code (PooledRedisClientManager ) which stuck at the GetClient method.

we use default pool size param (it is about 20 ) and that is too small we would have a Timeout error in our log files. However we have none and looks like it is not the case.

It seems there is a problem with ServiceStack Redis code since at that time Redis server working properly.

Please help us to check the problem. It is critical to our system to access Redis server

Service Stack v4.5

![servciestackredislockcontention](https://cloud.githubusercontent.com/assets/27766485/25174128/9f5eba50-2520-11e7-8379-c6dc3fbfdcc8.png)

**Comment by mythz** [comment]
This is going to be extremely hard to diagnose without a repro which is the first thing we're going to need in order to resolve the issue. 

Can you provide the complete Redis Configuration you're using, which OS/Environment/.NET Fx version the issue occurs in. Can you also upgrade to the latest version of ServiceStack so we're looking at the same implementation version.

Can you also provide the internal Stats print outs when this occurs by calling:

```csharp
((PooledRedisClientManager)redisManager).GetStats().ToJsv()
RedisStats.ToDictionary().ToJsv()
```

Obviously if you have a repro we can run locally that would be ideal.

**Comment by xplicit** [comment]
@citigodev can you also show expanded clr.dll (which takes 99.2%) from dottrace call tree?

**Comment by citigodev** [comment]
thanks guys for quick response
@mythz it is hard to reproduce that one because it only happen on our production and we don't want to let that happen again. Last time we had to increase more servers and it is working normal now.
We use default parameters and just one redis host for both read/write, the poolsize = 20

I will provide all the information tomorrow (it is night here and i'm not in the office)
//register Redis with Funq
container.Register<IRedisClientsManager>(c => new PooledRedisClientManager(new[] { redisConnection }, new[] { redisConnection }, null, AppConfigInfo.RedisDbNumber, AppConfigInfo.RedisPoolSize, null));
container.Register(c => c.Resolve<IRedisClientsManager>().GetCacheClient());

Regarding the repo it is quite big and sensitive information which I can't upload on Github. I will try to upgrade SS to latest version  but it is not a simple task 
@xplicit please check the image and let me know if you need more information

![untitled](https://cloud.githubusercontent.com/assets/27766485/25188335/e6737712-254f-11e7-9ddc-562e0a4ba692.png)

**Comment by xplicit** [comment]
Without .NET debug symbols we can't see what exactly spend time in GetClient(), but I think it's `Monitor.Wait` which is called when there are no available redis clients for write in a pool. This means that you should increase writeClients pool size to be sure that write client is returned almost immediately after code requests it. You can do it by passing `RedisClientManagerConfig` to `PooledRedisClientsManager`.

```csharp
container.Register<IRedisClientsManager>(c => new PooledRedisClientManager(
    new[] { redisConnection }, new[] { redisConnection }, 
    new RedisClientManagerConfig { MaxWritePoolSize = 100, MaxReadPoolSize =100 } ,
    AppConfigInfo.RedisDbNumber, AppConfigInfo.RedisPoolSize, null));
container.Register(c => c.Resolve<IRedisClientsManager>().GetCacheClient());
```

`Monitor.Wait` does not produce CPU spikes but long awaiting for a client might produce side effects in the user code and go into high CPU usage. 

When you'll increase buffers you can run trace again to be sure that `GetClient()` time spent has gone from profiler report and you will see in profiler what actually eats CPU, because with current time spending on awaiting `GetClient()` hides in a shade all processor-intensive methods which may produce high CPU peaks.

It's better to run profiler with CLR debug symbols, so we can see which methods spend time inside .NET too, not only ServiceStack methods.

**Comment by citigodev** [comment]
thanks much @xplicit ,

I will change the configuration as you suggested. I hope that will solve the problem. 

We use .Net 4.5 Window Server 2012 R2, IIS 8.5 

If the problem happen again I will send you the dottrace with CLR Debug symbols

**Comment by xplicit** [comment]
I will close it for now if you meet the issue again feel free to post it here, I'll reopen the issue.
