### ISSUE TITLE
QueueCommand does not call callback for all commands.

### ISSUE THREAD

**Issue by Harachie** [ServiceStack/Issues#540]
Hello,

I upgrades from one of the last V3 clients to the latest V4.5.8 version and encountered issues with QueueCommand within a transaction.

*edit* this is an issue with ServiceStack.Redis *edit end*

`
bool f, s;
            string key = Guid.NewGuid().ToString();

            using (var client = new RedisClient())
            {
                using (var trans = client.CreateTransaction())
                {
                    trans.QueueCommand(c => c.SetValueIfNotExists(key, "blah"), r => f = r);
                    trans.QueueCommand(c => c.SetValueIfNotExists(key, "blah"), r => s = r);
                    trans.Commit();
                }
            }
`

The callbacks are never called and so the values are not correctly set.
I expect f to be true and s to be false and that the callbacks are always called.

To fix this I added the OnSuccessBoolCall check in the QueuedRedisOperation.cs file for the BytesReadCommand.

`
if (OnSuccessBoolCallback != null)
                    {
                        OnSuccessBoolCallback(result == null ? false : Encoding.UTF8.GetString(result) == "OK");
                    }
`

I could not find any tests for this command. It seems to have changed from IntReadCommand to BytesReadCommand.
I could not find any breaking changes like this in the release notes, too.

Let me know whether this code fits your coding standards,
so I can create a pull request if you like.

Kind regards,
Bastian

**Comment by mythz** [comment]
Apologies for taking so long to respond, somehow missed the notification for this issue. This should now be fixed from [this commit](https://github.com/ServiceStack/ServiceStack.Redis/commit/05a9a63f66f171ad8f93c99ecb1d57af0c453380).

Which is available from v4.5.9 that's now [available on MyGet](http://docs.servicestack.net/myget).

BTW feel free to send PR's if you'd like, we can always refine and discuss it on the PR thread itself if needed. Would just need to [approve the Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSc-vKvdOx5lXGqmy6fkdCj-N0pALkVCx7QHYXojAuDSv_enNA/viewform) in order to accept PR's in future.
