### ISSUE TITLE
/types/typescript generator ignores DTOs named 'Service'.

### ISSUE THREAD

**Issue by Martaver** [ServiceStack/Issues#555]
Consider a basic service whose DTO interface definition is like so:

```
    public class Service 
    {
        public string Name {get; set;}
    }

    public class Company
    {
        public Service Test {get; set;}
    }

    [Route("/hello/{Name}")]    
    public class HelloWorld : IReturn<HelloWorldResponse>
    {
        public string Name { get; set; }    
    }

    public class HelloWorldResponse
    {
        public string Hello { get; set; }
        public Company Company {get; set;}
    } 
```

When I hit the URL `/types/typescript` I expect that the classes HelloWorld, HelloWorldResponse, Company and Test are created in Typescript.

Instead, the 'Service' class is omitted. If I rename the Service class to anything else, it's generated correctly. 

Maybe it's getting confused between my 'Service' and ServiceStack's 'Service' class?

**Comment by mythz** [comment]
No DTOs should be generated as you don't actually have a Service class that uses those Request DTOs?

**Comment by mythz** [comment]
Anyway its highly confusing to have a DTO called 'Service' so we're not going to invest any effort to allow it.

**Comment by Martaver** [comment]
Of course I have a Service class that uses them, the DTOs get generated
fine... Thought you might be interested that there seemed to be a weird
magic use case for 'Service' involved. By Reflection, this shouldn't be
necessary. It might be bad practice to name it as such, but I still wasted
a good deal of time on this.

**Comment by mythz** [comment]
It's unfortunate you've wasted time on this, but it really is a horribad name for a DTO. I mean you would've had to use a fully qualified namespace to force using it as a Request DTO when using a `Service` base class which alone should've sent off code smell warnings if the reuse of a name reserved for Service implementations in a DTO didn't.

Also you can't rely on reflection for this, all Request DTO names need to be unique in order to work in any non .NET languages where all DTOs are generated under the same namespace/module/etc. As a general rule whenever dealing with Types outside of a service boundary you should never be distinguishing them on their namespace, just their Type Name so c# namespaces should not leak outside of your service boundary.
