### ISSUE TITLE
Remaining columns are not mapped to DTO if a data type mismatch is encountered

### ISSUE THREAD

**Issue by c0shea** [ServiceStack/Issues#557]
When there is a data type mismatch, OrmLite is not mapping the remaining columns to the corresponding properties. Instead, `default(T)` is being used to populate the properties.

In the example LINQPad script I've included, OrmLite returns the correct number of rows, but only the `SaleDate` column is mapped. Because of the mismatch in my second column, `SaleTime`, between a `time` in SQL and a `DateTime` in my DTO, it fails to map the rest of the properties. However, if you change the `SaleTime` property in the DTO from a `DateTime` to `object`, everything works as expected.

![Second data type is wrong](https://i.imgur.com/gQw9SdN.png)

[OrmLite Mapping Bug.zip](https://github.com/ServiceStack/Issues/files/1175224/OrmLite.Mapping.Bug.zip)

**Comment by mythz** [comment]
Should now be fixed in [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/e862b647789b5fb388801f5c13c00107da66e21d) which is available from v4.5.13 that's now [available on MyGet](http://docs.servicestack.net/myget).

In future can you please send repro's using either [Gistlyn](http://gistlyn.com/?gist=a62b1e7a8da57c7d1fda95b3da5303eb) or just a stand-alone Console App as LINQPad scripts aren't useful to us, thanks.

**Comment by c0shea** [comment]
Thanks so much for fixing it that quickly. I hadn't heard of Gistlyn before but I'll be sure to use it next time.
