### ISSUE TITLE
UpdateUserAuth(IUserAuth existingUser, IUserAuth newUser) method in ServiceStack.Authentication.RavenDb does not check for existing user properly

### ISSUE THREAD

**Issue by zeko77** [ServiceStack/Issues#574]
Hi.
Version 4.5.14.0,
File RavenDbUserAuthRepository.cs,
Procedure UpdateUserAuth(IUserAuth existingUser, IUserAuth newUser) line 120,
existing user check is done by calling AssertNoExistingUser(newUser);.

UpdateUserAuth(IUserAuth existingUser, IUserAuth newUser, string password) in line 160 calls     AssertNoExistingUser(newUser, existingUser);

As a consequence, it is not possible to update existing user without setting password.

**Comment by mythz** [comment]
I'm assuming the issue was with [Line 120](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Authentication.RavenDb/RavenDbUserAuthRepository.cs#L120) calling `AssertNoExistingUser(newUser)` instead of `AssertNoExistingUser(newUser, existingUser)` which has now been fixed in [this commit](https://github.com/ServiceStack/ServiceStack/commit/6d5534cd49b7633a32a3f6dde993a6856ed78f3a), please let me know if you're referring to a different issue. 

This change is available from v5.0.0. that's now [available on MyGet](http://docs.servicestack.net/myget), please read [v5 changes](https://forums.servicestack.net/t/myget-pre-release-packages-upgraded-to-v5/4749) before upgrading.

**Comment by zeko77** [comment]
That is exactly it. Thank You.
