### ISSUE TITLE
Redis Sentinel Timeouts

### ISSUE THREAD

**Issue by lamnguyen108** [ServiceStack/Issues#592]
We're seeing a number of redis errors logged with the ServiceStack.Redis library that don't seem to be directly affecting the operation of our application, but they're still clogging up our logs, and we'd like to get rid of them, if possible.

We have sentinels set up with a master and a number of slaves. In our service, there's a singleton class that holds a IRedisClientsManager object that we use to dispatch commands. Our logs have a number of these errors that repeat several times:

**ServiceStack.Redis.RedisNativeClient",["SocketException in SendReceive, retrying..."
,"System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond**

and then this gets logged:

**ServiceStack.Redis.RedisNativeClient",["Exceeded timeout of 00:00:10"],{},{}]
ServiceStack.Redis.RedisSentinel",["Could not get active Sentinels from: 10.12.1.150"]**

We've never seen the application actually fail when these errors get logged, however. Are these errors anything to be concerned about, and what could we do to eliminate them?

**Comment by mythz** [comment]
This indicates that the Redis Client was unable to make a TCP connection with the remote Redis Server. The ServiceStack RedisClient includes a built in auto retry facility which is why you may have not seen these errors surfaced but they are potentially indicative of faulty network conditions that's preventing the Redis Client from being able to establish TCP Connections with the Redis Server or Sentinel. At which point there's nothing the Redis Client can do but retry to re-connect, which it does up to `RedisConfig.DefaultRetryTimeout` of 10000ms after which it will fail and throw a `RedisException`.
