### ISSUE TITLE
Incomplete data returned with Batch requests and CompressResponse

### ISSUE THREAD

**Issue by dlj** [ServiceStack/Issues#602]
A service with CompressResponse will only have the first item that is returned in the response.
It seems to be WriteBytesToResponse that closes the response even tho there more items waiting to be handled.

        public async void GetData()
        {

            var client = new JsonServiceClient("http://localhost:45375/");
            var compressedRtn = await client.GetAsync<List<Rtn>>(new CompresseTestdService.CompressedHelloRequest[0]);
            var normalRtn = await client.GetAsync<List<Rtn>>(new TestService.HelloRequest[0]);

            Debug.Assert(compressedRtn.ToJson() == normalRtn.ToJson());
        }
        
        public class Rtn
        {
            public int Id { get; set; }
        }

        [CompressResponse]
        public class CompresseTestdService : Service
        {
            public class CompressedHelloRequest : IReturn<List<Rtn>> { }

            public List<Rtn> Get(CompressedHelloRequest[] request)
            {
                return new List<Rtn>() { new Rtn() { Id = 1 }, new Rtn() { Id = 2 } };
            }
        }

        public class TestService : Service
        {
            public class HelloRequest : IReturn<List<Rtn>> { }

            public List<Rtn> Get(HelloRequest[] request)
            {
                return new List<Rtn>() { new Rtn() { Id = 1 }, new Rtn() { Id = 2 } };
            }
        }

**Comment by mythz** [comment]
It's not possible to compress an Auto Batched Response due to its design where each individual Response is [executed through the Request/Response filters individually](http://docs.servicestack.net/auto-batched-requests#request-execution-flow), whereas the `[CompressResponse]` needs to compress the entire Response in a single pass.

You'd instead need to avoid AutoBatched Requests for this and use a [Request DTO that inherits `List<Dto>` ](http://docs.servicestack.net/auto-batched-requests#defining-a-request-dto-to-accept-a-collection-of-types), e.g:

```csharp
public class CompressedHelloRequests : List<CompressedHelloRequest>, IReturn<List<Rtn>> { }

[CompressResponse]
public class CompresseTestdService : Service
{
    public List<Rtn> Get(CompressedHelloRequests request)
    {
        return new List<Rtn> { new Rtn { Id = 1 }, new Rtn { Id = 2 } };
    }
}
```
