### ISSUE TITLE
Exception when getting metadata

### ISSUE THREAD

**Issue by marko444** [ServiceStack/Issues#624]
Calling http://myserver/api/types/metadata throws exception in version 5.1 and later.

Debugged with latest SS: 

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.Reflection.RuntimeMethodInfo' to type 'System.Reflection.FieldInfo'.
  Source=ServiceStack
  StackTrace:
   at ServiceStack.NativeTypes.MetadataTypesGenerator.ToType(Type type) in c:\Dev\ServiceStack\src\ServiceStack\NativeTypes\NativeTypesMetadata.cs:line 400
```

Exception is thrown here
`var enumMember = (FieldInfo)type.GetMember(name).First();`

Type is a simple enum:
```
    public enum ComparisonOperator
    {
        Equals = 0,
        NotEqual = 1,
...    
}

```

**Comment by mythz** [comment]
The issue is because the you're using the `Equals` Enum member which conflicts with the `Equals()` methods on Enum types which the Reflection API also returns. I've used [BindingFlags in this commit](https://github.com/ServiceStack/ServiceStack/commit/6f9ce072b0853d51e4bbe0f25ca0f1e7a0570559) to limit the members returned which should resolve this issue. 

This change is available from v5.1.1 that's [now on MyGet](http://docs.servicestack.net/myget).
