### ISSUE TITLE
FromJson strange deserialization

### ISSUE THREAD

**Issue by marko444** [ServiceStack/Issues#635]
Hello!

Is it possible to throw an exception when deserializer encounters an empty array (bad user input)?

Code:
```
        [Fact]
        public void ShouldFailWhenDeserializingArrayToString()
        {
            var json = @"{""Property"":[]}";

            // var ser = new JavaScriptSerializer();
            // var actual = ser.Deserialize<SampleClass>(json); // System.InvalidOperationException: 'Type 'System.String' is not supported for deserialization of an array.'
            // var actual = Newtonsoft.Json.JsonConvert.DeserializeObject<SampleClass>(json); // Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: [. Path 'Property', line 1, position 13.'

            var actual = json.FromJson<SampleClass>();

            Assert.NotEqual("[]", actual.Property);
        }

    public class SampleClass
    {
        public string Property { get; set; }
    }
```

**Comment by mythz** [comment]
No ServiceStack.Text was designed to deserialise as much as possible without error. The configuration to have ServiceStack.Text throw instead of log ist to set:

    Env.Strict = true;


But otherwise new serialisers like ServiceStack’s JSON.parse() will throw Exceptions on malformed JSON, but won’t be going back and change how ServiceStack.Text works, if you want a more stricter JSON Serializer you’ll need to use a different one.
