### ISSUE TITLE
Self Host Custom Path

### ISSUE THREAD

**Issue by dpbevin** [ServiceStack/Issues#64]
I would like to be able to host a ServiceStack service from both IIS (ASP.NET) and self-hosted and still use the same Service implementations. My static files need to be hosted from the base URL and the REST api to be hosted from a custom path (e.g. "/api".

Following the instructions this page https://github.com/ServiceStack/ServiceStack/wiki/Run-servicestack-side-by-side-with-another-web-framework I need to use the custom path "api".

But then there's no way (to my knowledge) of hosting the **REST only** portion of a self-hosted service to "/api" without modifying the RouteAttribute for each of the services I've implemented. Please correct me if I'm wrong about this. I'd like to serve my static files from the base URL and my REST api from "/api" to be consistent with how it works under IIS.

I have two implementations of my application host - one derives from AppHostBase (ASP.NET) and the other from AppHostHttpListenerPoolBase (Self-Hosted).

The IIS hosted one works fine. The self hosted one always hosts are the root URL. I've tried setting the handler path in `AppHostHttpListenerPoolBase(serviceName, handlerPath, assembliesWithServices)` and setting `HostConfig.HandlerFactoryPath` but to no avail.

**Comment by wbrussell** [comment]
@mythz I implemented this solution for overriding route attributes and I noticed it works on user services but not on the builtin authorization, assignroles, and registration services.  When those request types come in, they don't have any route attributes so the "/api" can't be inserted.

Any way to overcome this so that all rest endpoints have the same base?
Thanks,
Brian

**Comment by mythz** [comment]
@wbrussell have you tried [adding Routes dynamically](https://github.com/ServiceStack/ServiceStack/wiki/Routing#dynamically-adding-route-attributes)?

**Comment by wbrussell** [comment]
From what I gather, this would still produce different base rest paths.  It looks like convention-base routes for user and built-in services would need to have the attributes added to them so that they can be modified.  That doesn't sound like something I should be doing to the built-in routes.

In the spirit of @dpbevin original use case, those services aren't going to be on the same base path for self-host and thus would require special handling in the client rest paths.

**Comment by mythz** [comment]
This is required for any Service that doesn't have `[Route]` attributes. Since you can't add attributes to built-in Services, you would need to add the Route Attributes dynamically.

**Comment by wbrussell** [comment]
Ok, thanks.
