### ISSUE TITLE
Json Bool Handling changed between version 5.1 and 5.2, still a problem in 5.4

### ISSUE THREAD

**Issue by MarkLFT** [ServiceStack/Issues#648]
I have a simple API method that receives the following JSON in the request.

{"Confirmations":[{"ChangeId":126552616,"Confirmed":true}]}

The request does not contain any other data.
In version 5.1 this works are planned.  But if I upgrade the server to version 5.2 or 5.4, the API request fails with the following error.

{
    "IsSucceed": false,
    "ResponseStatus": {
        "ErrorCode": "ArgumentNullException",
        "Message": "Value cannot be null.\r\nParameter name: source",
        "Errors": [
            {
                "ErrorCode": "ArgumentNullException",
                "FieldName": "source",
                "Message": "Value cannot be null.\r\n"
            }
        ]
    }
}

When I step through the source of the API in the server, I find that on the later versions the request.Confirmations collection is null.

I have ran numerous tests using Postman and Fiddler, and I have found in the later versions, if I wrap the true value in quotes as below, the newer versions work also.

{"Confirmations":[{"ChangeId":126552616,"Confirmed":"true"}]}

Your JsonHttpClient() generates json as the unquoted version. 

According to my research, the json standard says that the unquoted version of true and false should be acceptable.  But it seems version 5.2 and 5.4 of ServiceStack disagree.

**Comment by mythz** [comment]
Boolean values should be unquoted should be unquoted in JSON. 

Please provide the DTO that this payload is trying to deserialize into. Please also provide the raw HTTP Request/Response which you can get using a HTTP packet sniffer like [Fiddler](https://www.telerik.com/fiddler) as there's something else that going wrong since the JSON deserializes into the natural DTO for this payload as expected:

```csharp
var json = "{\"Confirmations\":[{\"ChangeId\":126552616,\"Confirmed\":true}]}";

public class Dto
{
    public List<Confirmation> Confirmations { get; set; }
}

public class Confirmation
{
    public int ChangeId { get; set; }
    public bool Confirmed { get; set; }
}

var dto = json.FromJson<Dto>();

dto.PrintDump();
```

If you can you can try modifying this [Live Gist on Gistlyn](https://gistlyn.com/?gist=d3ff39c7052b5b0d6e5dfe4d5e570eb9) to repro the issue.

**Comment by MarkLFT** [comment]
The DTO's are as follows.

 [Route("/confirmations", "PUT")]
    public class PutConfirmed : IReturn<PutConfirmedResponse>
    {
        #region Public Properties
        public List<Confirmation> Confirmations { get; set; }
        #endregion Public Properties
    }

public class Confirmation
    {
        #region Public Constructors
        public Confirmation()
        {
            ChangeId = 0;
            Confirmed = false;
        }
        #endregion Public Constructors
        #region Public Properties
        public int ChangeId { get; set; }
        public bool Confirmed { get; set; }
        #endregion Public Properties
    }

public class PutConfirmedResponse
    {
        #region Public Properties
        public bool IsSucceed { get; set; }
        public ResponseStatus ResponseStatus { get; set; }
        #endregion Public Properties
    }

**Comment by mythz** [comment]
I've updated the [Gistlyn example with your DTO classes](https://gistlyn.com/?gist=d3ff39c7052b5b0d6e5dfe4d5e570eb9) showing v5.4.0 deserializes without issue.

Please include the raw HTTP Request/Response Headers and any custom JSON configuration you're using if you have any.

**Comment by MarkLFT** [comment]
I have to used any custom JSON Configurations, I wouldn't know how.

When using 5.1 this is the raw header captured in Fiddler

PUT http://cyeri.lftmail.com:6003/api/confirmations HTTP/1.1
Content-Type: application/json
cache-control: no-cache
Postman-Token: 44d00839-92df-46f5-ae99-e5e5075ddea6
User-Agent: PostmanRuntime/7.3.0
Accept: */*
Host: cyeri.lftmail.com:6003
accept-encoding: gzip, deflate
content-length: 59
Connection: keep-alive

{"Confirmations":[{"ChangeId":126552616,"Confirmed":true}]}

And this is the raw response received, also form Fiddler.

HTTP/1.1 200 OK
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8
Vary: Accept
Server: Microsoft-HTTPAPI/2.0
X-Powered-By: ServiceStack/5.10 NET45 Win32NT/.NET
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: Content-Type
Date: Fri, 19 Oct 2018 02:10:34 GMT

12
{"IsSucceed":true}
0

**Comment by mythz** [comment]
This request succeeds, so what’s the issue?

**Comment by MarkLFT** [comment]
As I wrote, that is using version 5.1, which works, it is newer versions that do not work.  I will have to change versions again to demonstrate a failure.  I will do that later.

**Comment by mythz** [comment]
I need details of the actual issue. The primary goal of every issue is to [provide a repro](https://github.com/ServiceStack/Issues#servicestack-issues), I've added your DTOs in a live Gistlyn example which serilalizes as expected.

I've now also created a stand-alone integration test using your DTOs in [this commit](https://github.com/ServiceStack/ServiceStack/commit/1beb7d65f47208688f7f9d3ee6b97038bddf8dac) which also works without issue.

I have been unable to reproduce the issue, I will now need a stand-alone example I can run locally to repro the issue. Please upload a stand-alone project on GitHub I can run locally to repro the issue in order to  be able to investigate any further.

**Comment by MarkLFT** [comment]
Sorry, I don't have any more time I can waste on this.  It is working on 5.1, so I have just rolled the service back to use the that version of the libraries.  I appreciate you need more info, but I just don't have the time.

From what I can see, SS has very few dependencies when used on .Net 4.x so nothing else in the windows service should be affecting it. By just changing the version of the SS libraries it either works or throws an error.  Version 5.1 and below works, version 5.2 and above throws the null error.   I have changed absolutely nothing else in the code apart from the versions of the SS nuget packages I installed.

Again, I am testing with Postman, so it is not a client error.

On the server side, the request contains a null value where it should be a List<>, and it fails on the first line of code that checks the List is not null.  So I know the problem is not with the code  behind this method, as it never gets accessed.

So, whether you can make it work or fail or not, I have proven the issue is within SS somewhere. 

Thanks for you effort until now.  But as you say with out me making a standalone version of the service, you can do nothing else.  So I guess we will never know the cause, until someone else comes across it.

**Comment by mythz** [comment]
I haven’t seen proof of a Request that fails yet and given it’s not reproducible the issue may be due to some other environmental factors that’s not provided which is why I’ll need a stand-alone repro to be able to investigate further so I’m able to identify what the cause of the issue really is.

Feel free to submit a stand-alone repro if you get time in future.
