### ISSUE TITLE
Error serializing message from mq server

### ISSUE THREAD

**Issue by vyommalhotra** [ServiceStack/Issues#664]
I have a little bit of an odd error showing up in my application which I am unable to track down. Maybe you have some ideas of how to figure out whats going on here.

I have a simple .NET Core Console Application containerized with docker and running on an Amazon ECS test environment. It consumes SQS queues and publishes SNS messages. It has been running for a few days and at odd times (late night or after midnight), I see the following error in the logs because I have Service Stack debugging mode turned on:

`2019-04-02 03:58:55 ERROR: Error serializing message from mq server: A task was canceled., Exception: A task was canceled.`

`2019-04-01 20:30:11 ERROR: Error serializing message from mq server: A task was canceled., Exception: A task was canceled.`

I regularly see about 2 errors every night.
Its in my test environment and I did not push any messages to the queue at this time. Is this something to be concerned about because the application seems to be working fine otherwise.

**Comment by mythz** [comment]
The error message is likely misleading, it occurs here: https://github.com/ServiceStack/ServiceStack/blob/a5623a3caa64b1e3670e154fe404ba61d7470571/src/ServiceStack/Messaging/MessageHandler.cs#L84

Where it's common for any exception thrown to be the result of not being able to deserialize the message however in this case the cause of the Exception was: `A task was canceled` which is [typically due to 2 reasons](https://stackoverflow.com/a/29214208/85785).

Essentially the async request making the request to fetch to see if there's any messages to process was cancelled which can either be due to timeout or if the AppDomain or worker was being shutdown. Either way as the message wasn't ACK'ed no message should've been lost.

**Comment by vyommalhotra** [comment]
Thanks.

Whats the fix for this? Whats the default timeout and how can I increase it for those requests?

**Comment by mythz** [comment]
There isn't any, the [DefaultWaitTime is already at the Max Wait Time](https://github.com/ServiceStack/ServiceStack.Aws/blob/master/src/ServiceStack.Aws/Sqs/SqsQueueDefinition.cs#L6). Requests to AWS services can timeout, just ignore the warnings.

**Comment by mythz** [comment]
I've ignore cancelled tasks from being logged in this commit https://github.com/ServiceStack/ServiceStack/commit/c42e324fe7cec75b123d9070bd815adf01f56971
