### ISSUE TITLE
VirtualFileSystem MemoryFile from MemoryStream

### ISSUE THREAD

**Issue by ICO-PI** [ServiceStack/Issues#668]
Hi,

We are registering a new `MemoryVirtualFiles` and adding a file from a MemoryStream. When requesting the file, it hangs indefinitely. We are migrating from 5.1 to 5.5, this works in 5.1. 

Tracing a bit, it seems that `InMemoryVirtualFile.Refresh` is called, the `textcontents` is null and `bytescontents` has the file content. The setter of `textcontents` tries to set `ByteContents = value.ToUtf8Bytes();` which fails with a null exception since `value` is null.

See sample, thanks!
[ConsoleApp2.zip](https://github.com/ServiceStack/Issues/files/3085008/ConsoleApp2.zip)

**Comment by mythz** [comment]
Thanks for the repro, this should now be resolved with [this commit](https://github.com/ServiceStack/ServiceStack/commit/dd2612d2df34967e074417f1d90709f0aba6bc04) which is available from v5.5.1 that's [now available on MyGet](https://docs.servicestack.net/myget).

FYI now that an [Empty MemoryVirtualFiles now registered in VirtualFileSources](https://docs.servicestack.net/releases/v5.5#empty-memoryvirtualfiles-now-registered-in-virtualfilesources) in v5.5, it's recommended you use the existing `MemoryVirtualFiles` instead of adding another one which you can do with:

```csharp
public class AppHost : AppSelfHostBase
{
    public AppHost()
      : base("HttpListener Self-Host", typeof(HelloService).Assembly) { }

    public override void Configure(Funq.Container container)
    {
        var memoryProvider = (MemoryVirtualFiles)this.InsertVirtualFileSources.First(x => x is MemoryVirtualFiles);
        System.IO.MemoryStream memStream = new System.IO.MemoryStream();
        System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("ConsoleApp2.image.png").CopyTo(memStream);
        memStream.Seek(0, System.IO.SeekOrigin.Begin);

        memoryProvider.WriteFile("image.png", memStream);
    }
}
```
