### ISSUE TITLE
vs 2017 update ServiceStack reference error

### ISSUE THREAD

**Issue by wuwo1952368901** [ServiceStack/Issues#670]
when i update reference have this error:  Instances that do not set object references to objects

**Comment by mythz** [comment]
I can't repro it with the latest update of VS 2017 and latest update of ServiceStack VS 2.0.0:

![image](https://user-images.githubusercontent.com/89361/56875754-c2b25980-6a10-11e9-9708-85742a3b9c4b.png)

Adds/Update References for both TypeScript and C# DTOs without issue.

I'll [need a local repro](https://github.com/ServiceStack/Issues#servicestack-issues) in order to be able investigate further.

An alternative to using **Update ServiceStack Reference** in the GUI, is to use the [web .NET Core tool](https://docs.servicestack.net/web-tool)

Which you can install with:

    $ dotnet tool install --global web 

Then you can update all TypeScript `dtos.ts` rerefences with:

    $ web ts

Or all C# `.dtos.cs` references with:

    $ web cs
