### ISSUE TITLE
Issue with typescript-ref and grpc

### ISSUE THREAD

**Issue by ludydoo** [ServiceStack/Issues#690]
Steps to reproduce: 

1. `web new grpc`
2. create any angular project with `ng new`, then `npm install @servicestack/cli @servicestack/client`
3. `typescript-ref https://localhost:5001`

```
C:\Users\bliblou\work\wspc>typescript-ref https://localhost:5001
(node:5364) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
socket hang up
```

The server logs show

```
fail: Microsoft.AspNetCore.Server.Kestrel[0]
      HTTP/2 over TLS was not negotiated on an HTTP/2-only endpoint.
```

Then, if I remove 

```
  "Kestrel": {
    "EndpointDefaults": {
      "Protocols": "Http2"
    }
  }
```

from `appsettings.json`

Then it works. But then I believe `grpc` doesn't work anymore.

**Comment by mythz** [comment]
It's because not many HTTP Clients support HTTP/2, can you try with the latest v0.0.43 of the [web dotnet tool](https://docs.servicestack.net/web-tool), e.g:

$ dotnet tool install --global web 

Then can run with:

$ web ts https://localhost:5001

If you had a previous version installed, update with:

    $ dotnet tool update -g web

**Comment by ludydoo** [comment]
That did solve it thank you

**Comment by mythz** [comment]
Great. glad to hear it!
