### ISSUE TITLE
OrmLite table created from model incorrectly

### ISSUE THREAD

**Issue by JDBarndt** [ServiceStack/Issues#700]
Hi,

Using 5.7.1 packages, I have a table I'm attempting to create in SQL Server using the following model:

```
[Alias("Theme")]
public class DbTheme : IHasId<int>
{
	[ApiMember(Description = "Unique ID of the Theme.")]
	[AutoIncrement]
	public int Id { get; set; }

	[ApiMember(Description = "Name of the Theme.")]
	[Index(Unique = true)]
	[Required]
	[StringLength(100)]
	public string Name { get; set; }

	[ApiMember(Description = "DateTime Theme was last modified.")]
	[Default(OrmLiteVariables.SystemUtc)]
	[Required]
	public DateTime Modified { get; set; }

	[ApiMember(Description = "User who last modified this Theme.")]
	[References(typeof(DbUser))]
	[Required]
	public short Modifier { get; set; }
}
```
The resulting SQL generated to create the table is the following:

```
CREATE TABLE "Theme" 
(
  "Id" INTEGER PRIMARY KEY IDENTITY(1,1), 
  "Name" NVARCHAR(100) UNIQUE NONCLUSTERED, 
  "Modified" DATETIME NOT NULL DEFAULT (SYSUTCDATETIME()), 
  "Modifier" INTEGER NOT NULL, 

  CONSTRAINT "FK_Theme_User_Modifier" FOREIGN KEY ("Modifier") REFERENCES "User" ("Id") 
); 

CREATE UNIQUE NONCLUSTERED INDEX uidx_theme_name ON "Theme" ("Name"); 
```

There are two issues/concerns I'm seeing:

1. The "Name" field is being created as nullable. It is missing the NOT NULL flag. If I remove the [Index] attribute above the field and create the table, the column is created with NOT NULL as expected, but no unique index.
2. For the unique index, it actually is creating two indexes. One is a unique key and the other is the explicit index created post-table creation. Is this expected?

Thank you.

**Comment by mythz** [comment]
Appears the this issue was added in the SQL Sever 2014+ Dialect Providers as <= SqlServer2012 will create the property as a `NOT NULL` column with only a single unique constraint definition as you're expecting.

This issue should now be resolved in [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/ac322896a3498b0ad3cbdca1f806d6116f92b0d6) where all SQL Server Dialect providers retain the same expected behavior.

This change is available from v5.7.1 that's now [available on MyGet](https://docs.servicestack.net/myget).
