### ISSUE TITLE
OrmLite: InsertFilter fires before InsertAsync/UpdateInsert in SaveAllAsync

### ISSUE THREAD

**Issue by rlightner** [ServiceStack/Issues#701]
https://github.com/ServiceStack/ServiceStack.OrmLite/blob/a5e33212314decbb857664504ab81c658ef181a1/src/ServiceStack.OrmLite/Async/OrmLiteWriteCommandExtensionsAsync.cs#L384

When using an InsertFilter/UpdateFilter, the Select statement is returned instead of the Insert Statement. Also if the model has an Auto Incremented column, InsertFilter is never fired.

Same issue is present for UpdateAsync in this method.

**Comment by mythz** [comment]
This is the expected behavior, the Filters are executed before the statement is constructed so that the filters can modify the object before construction as [required for maintaining Audit Information](https://github.com/ServiceStack/ServiceStack.OrmLite#global-insert--update-filters).

If you need access to the SQL after execution you can use the [AfterExecFilter](https://github.com/ServiceStack/ServiceStack.OrmLite#beforeexecfilter-and-afterexecfilter-filters)
