### ISSUE TITLE
MemoryServerEvents.Subscriptions never unsubscribe

### ISSUE THREAD

**Issue by lomithrani** [ServiceStack/Issues#705]
I'm Using Servicestack `v5.8.0` ` netcoreapp3.1` `x64 `I use the default `Plugins.Add(new ServerEventsFeature());` (and have tried a couple of others including redis).

I subscribe using javascriptclient , and it shows up fine in the /events-subscribers   but I can never unsubscribe and if I close my subscriptions persists in /event-subscribers.

**Comment by mythz** [comment]
I'd need some clear steps/way to repro this behavior.

What client SSE JavaScript client library are you using? Are you saying that if you close the browser window and wait beyond the Idle Timeout (30s) the subscription never unsubscribes?

What if you either manually call the `unRegisterUrl` populated in your [onConnect handler](https://docs.servicestack.net/server-events#onupdate-notification). If you're using [ss-utils.js](https://docs.servicestack.net/ss-utils-js) you can call:

```js
$.ss.disposeServerEvents();
```

Otherwise if you're using the [@servicestack/client](https://docs.servicestack.net/typescript-server-events-client) npm package you can call `stop()`, e.g:

```ts
var const client = new ServerEventsClient(...)
    .start();
//...
client.stop();
```

**Comment by lomithrani** [comment]
As per the doc I used
`var source = new EventSource(`/event-stream?channel=doc_${id}&t=${new Date().getTime()}`);`

right now I use 
` $.ss.eventSource = new EventSource(`/event-stream?channel=doc_${id}&t=${new Date().getTime()}`);`

`$.ss.disposeServerEvents();` returns undefined

I tried to call directly with get request /event-unregister?channel=@channel 

and yes it persist beyond the idle time event if I close my browser. I seem to be able to add as much subscriptions I want I just can never unsubscribe

**Comment by mythz** [comment]
Which docs are you following, the [JavaScript Server Events Client](https://docs.servicestack.net/javascript-server-events-client) docs?

You're suppose to use `handleServerEvents()` to register your connection if you're using ss-utils.js, e.g:

```js
var source = new EventSource('/event-stream?channel=channel&t=' + new Date().getTime());
$(source).handleServerEvents({
  //..
});
```

Please update your code to use the official API, i.e. instead of setting internal variables yourself, that should be done by the public APIs.

If there's still an issue, please post a minimal repro on GitHub that I can run locally to repro the issue.

**Comment by lomithrani** [comment]
I did do that at first using said docs but it didn't help. I'll try to provide you with a minimal repro thankyou.
