### ISSUE TITLE
Empty string argument is getting converted into a zero width space character

### ISSUE THREAD

**Issue by rajujain33** [ServiceStack/Issues#712]
Hi,
My request object contains a property of type object and while sending that property at empty string, in service implementation we are getting a zero width character.

Issue is reproducable 
https://github.com/rajujain33/ServiceStackZeroWidthCharacterIssue.git

**Comment by mythz** [comment]
Note: this behavior is due to using an unknown `object` type which [should be avoided](https://docs.servicestack.net/customize-json-responses#avoid-unknown-types-in-servicecontracts).

Either way this specific issue has been resolved in [this commit](https://github.com/ServiceStack/ServiceStack.Text/commit/f7337e62a3e3ed25b10cf342a7b45b72b53fc5b4). This change is now available in v5.8.1 that's now [available on MyGet](https://docs.servicestack.net/myget).

I've also noticed your Test Service returns a value type (bool), please note [Services should only return Reference Types](https://docs.servicestack.net/service-return-types#services-should-only-return-reference-types).
