### ISSUE TITLE
Cannot load dependency System.Runtime.CompilerServices.Unsafe

### ISSUE THREAD

**Issue by FranciscoRZ** [ServiceStack/Issues#714]
Hello,

I'm trying to use ServiceStack to get data from the AlphaVantage API in an Excel Add-in.

Unfortunately while my solution builds when ServiceStack is called I'm getting the following error in Excel :
  
    Cannot load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The definition found in the assembly manifest does not correspond to the referenced assembly (Exception HRESULT: 0x80131040).

This is after a fresh install of ServiceStack through NuGet. Any ideas as to what might be causing this?

**Comment by mythz** [comment]
Unfortunately these issues are [runtime binding issues](https://docs.servicestack.net/templates-corefx#troubleshooting) which are unique to each project. 

You can try [adding a runtime binding redirect](https://stackoverflow.com/a/55329952/85785) to see if it helps otherwise the best thing you can try is upgrading the .NET Framework version to see if that resolves it.

Otherwise the [troubleshooting section](https://docs.servicestack.net/templates-corefx#troubleshooting) lists a few other steps you can try.
