### ISSUE TITLE
ServiceStack.Extensions.Core

### ISSUE THREAD

**Issue by mikkeljohnsen** [ServiceStack/Issues#717]
I can't find the NuGet package "ServiceStack.Extensions.Core". I need that to enable gRPC.

Can you create that package aswell ?

**Comment by mythz** [comment]
There is no `.Core` because [ServiceStack.Extensions](https://www.nuget.org/packages/ServiceStack.Extensions) is a .NET Core 3.1 only library (i.e. not multi-targeted) and can only be used in .NET Core 3.1 Apps.

I'd recommend starting from the [grpc](https://github.com/NetCoreTemplates/grpc) project.
