### ISSUE TITLE
RemoveFromCache extension method on Request not available after updating from 5.9.2 to 5.10.4

### ISSUE THREAD

**Issue by zeko77** [ServiceStack/Issues#750]
Has extension method on Request "RemoveFromCache" been removed?
As suggested on https://docs.servicestack.net/caching
this line of code:

`return base.Request.RemoveFromCache(base.Cache, cacheKey);`

complains that there is no extension method after updating from 5.9.2 to 5.10.4

I have worked around this with:
Cache.RemoveByPattern($"{request.Key}*");

Is this by design now as I could not find a breaking change like this.

**Comment by mythz** [comment]
Looks like it from the async caching provider refactor as part of [this commit](https://github.com/ServiceStack/ServiceStack/commit/9b4ff3ad7f326e2dabfd685988c5413c2d989b5a#diff-c0c4b6aefae711ebbf2ab330485f6ddcbf57c2ea1606184020e1552f97d6dab1).

The original definition was:

```csharp
public static void RemoveFromCache(
    this IRequest requestContext, ICacheClient cacheClient, params string[] cacheKeys)
{
    cacheClient.ClearCaches(cacheKeys);
}
```

Since it wasn't being referenced in code-base or tests anywhere & the ext method wasn't using `IRequest` I thought it was an undocumented API that was safe to remove. should've checked the docs.

Anyway you'd call either the sync or async version:

```csharp
base.Cache.RemoveFromCache(base.Cache, cacheKey);

await CacheAsync.ClearCachesAsync(cacheKeys);
```
