### ISSUE TITLE
Licensed ServiceStack.Redis is slower than trial license when getting data

### ISSUE THREAD

**Issue by javierormeno** [ServiceStack/Issues#776]
I recently purchased the ServiceStack.Redis commercial license and load tested it to retrieve data stored in Redis AWS.

Tests with the Jmeter tool show lower response times when using the trial license.

Comercial License:
![image](https://user-images.githubusercontent.com/58050487/171518880-14f4c389-8917-4056-b780-6e18650c8024.png)

Trial License:
![thumbnail_image002](https://user-images.githubusercontent.com/58050487/171518813-3c547513-a67c-4c1c-bfe1-9eb7d571fdd5.png)

I tried to add the license key in all the ways specified in the documentation.

**Comment by Layoric** [comment]
Hi @javierormeno,

This Issue tracker is for reporting reproducible bugs/issues only. 

JMeter is a HTTP load tester, so there are many variables that could go into the latency you are seeing between tests. The source code to ServiceStack.Redis is fully available and you'll see there is no performance impedance regardless of license or any other factor for that matter. 

Also note, that if you were testing Redis directly, most operations are sub millisecond, again, what you are measuring here takes into account not only the latency of the whole web stack but also network latency between the client machine and HTTP server.

If you are having issues with performance and want some advice, please reach out in the customer forums, since this issues list is only for reproducible bugs.

**Comment by mythz** [comment]
I'll also add that your conclusion that the performance differences is due to License type isn't possible since Trial & Commercial License are treated the same at runtime & that runtime cost is negligible since it's just incrementing a number and performing 1 enum bit mask comparison operation, i.e. if you profiled it, it would be inconsequential.
