### ISSUE TITLE
non-windows support

### ISSUE THREAD

**Issue by waynebrantley** [ServiceStack/Issues#789]
### Describe the issue

We use servicestack and that has a dependency on system.common.drawing.
Not sure why the 'servicestack' main library needs to do drawing for handling my api requests - but evidently it does.
We use an apphost and a basic api to do a rest service type of scenario.

We would like to run this in Azure Container App - which requires linux compatiblity.

Any chance of removing that dependency (making a windows assembly or something for those that need that)?

### Reproduction

view dependencies:  https://www.nuget.org/packages/ServiceStack

### Expected behavior

Be linux compatible

### System Info

```shell
.net 6.
```

### Validations

- [X] Confirm [Issue is reproducible](https://github.com/ServiceStack/Issues#how-to-create-a-good-bug-report) from the information provided
- [X] Have an active commercial ServiceStack License _(GitHub Username is [registered on Support page](https://account.servicestack.net/account/support))_

**Comment by mythz** [comment]
ServiceStack has been running on Linux for over a decade, can you please provide the full StackTrace of the Exception on Linux.

**Comment by mythz** [comment]
I'd be surprised if it caused any issues on Linux since it's not used by any code path in the framework, it was used at one stage to resize profile images of MS Graph OAuth provider to fit within cookies 4k limit, but this has since been rewritten to use an alternative workaround.

I'm assuming you're just seeing some analysis tool errors, instead of any actual issues at runtime, but as it's no longer being used, I've moved the System.Drawing implementation to ServiceStack.Desktop.

This change is available from v6.8.1+ that's now [available on MyGet](https://docs.servicestack.net/myget).
